### ISSUE TITLE
Trigger clippy: empty doc comment

### ISSUE THREAD

**Issue by Luv-Ray** [pest-parser/pest#1000]
It generated 1 warning when I run `cargo clippy`:
```
warning: empty doc comment
  --> cypherparser/src/parser.rs:21:10
   |
21 | #[derive(Parser)]
   |          ^^^^^^
   |
   = help: consider removing or filling it
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#empty_docs
   = note: `#[warn(clippy::empty_docs)]` on by default
   = note: this warning originates in the derive macro `Parser` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I have checked my `grammer.pest` and be sure that I have not written any empty doc comments like `/// ` or `// `. I want to know if there are any other situations in which pest would generate empty doc comments.

Thanks.

**Comment by HoloTheDrunk** [comment]
Likely #987 and the fix just hasn't been deployed yet since it was right after the 2.7.8 release.

**Comment by Luv-Ray** [comment]
Thanks.
