### ISSUE TITLE
add some basic types to pest so it improves grammar readability

### ISSUE THREAD

**Issue by lwandrebeck** [pest-parser/pest#103]
I think having some already defined types would help to enhance readability.
alpha,
decdigit,
hexdigit,
octdigit,
alphanumeric,
space,
signedint,
unsignedint,
signedfloat,
unsignedfloat,
singlequoted,
doublequoted

and maybe a couple others, but these should cover most common needs.

**Comment by dragostis** [comment]
I've assigned this myself for now, but would you be willing to try this out once 1.0 is released?

**Comment by Keats** [comment]
I'll take it if no one gets to it first

**Comment by lwandrebeck** [comment]
`impl_rdp! {
    grammar! {
        plus   = { ["+"] }
        minus  = { ["-"] }
        sign = { minus | plus }
        alpha = { i['a'..'z'] }
        minalpha = { ['a'..'z'] }
        capalpha = { ['A'..'Z'] }
        digit = { ['0'..'9'] }
        alphanum = { alpha | digit }
        minalphanum = { minalpha | digit }
        capalphanum = { capalpha | digit }
        octdigit = { ['0'..'7'] }
        hexdigit = { ['0'..'9'] | i['a'..'f'] }
        uint = { ['0'] | ( ['1'..'9'] ~ digit* ) }
        sint = { sign ~ uint }
        exp = { i['e'] }
        ufloat = { uint ~ ['.'] ~ digit* ~ ( exp ~ ( uint | sint ))? }
        sfloat = { sign ~ ufloat }
        octnum = { ['0'] ~ octdigit+ }
        hexnum = { ["0x"] ~ hexdigit+ }
        dquoted = { !["\""] ~ any }
        squoted = { !['\''] ~ any }
        btquoted = { ![`\``] ~ any }
    }
}
`

Here is a quick shot at it. I’d be very willing to test it once 1.0 is released, as I need it for my pet project.
@Keats feel free to get to it :)

**Comment by dragostis** [comment]
It would probably be a good idea to have pest default rules look differently compared with your own rules. This would definitely make writing grammars a bit more predictable.

**Comment by lwandrebeck** [comment]
Feel free to pick up some, all, rename rules. I guess this would have to be coded in « pure » rust instead of already defined pest grammar ?

**Comment by dragostis** [comment]
@lwandrebeck Not necessarily. But there should be an obvious difference between them, I'd say.

**Comment by Keats** [comment]
Maybe we can use `::` as delimiter, like `:alpha:`, `:int:` etc?

**Comment by dragostis** [comment]
@Keats Could be an idea. I was thinking about a simpler `ALL_CAPS` solution, and maybe make `WHITESPACE` and `COMMENT` the same.

**Comment by sjmielke** [comment]
It would be nice to have especially classes like `alpha` as unicode-aware variants as well, like in unicode-aware PCRE ( http://www.regular-expressions.info/posixbrackets.html ). It's probably a lot harder to write custom grammars including all these characters, so maybe some way to integrate them into the library would be preferable? _(just 2¢ from a Rust newbie, no idea how you recognize characters and if you can use some library implementing those Unicode classes)_

**Comment by dragostis** [comment]
@sjmielke That's a very good point! We can definitely make use of Rust's `std` to make this happen.

**Comment by lwandrebeck** [comment]
I’d vote then for a clear split between ascii helpers and u8/16/32/x (unicode that is, not rust types) helpers.
For example, ;alpha; for ascii, :u8alpha: for the utf8 version or something. As Pest is language oriented, that would allow for a clear meaning about the way data is processed (one would like to parse french, german, whatever, another would like to process some ascii IT language (most ? all ?)).

**Comment by dragostis** [comment]
Sure, but I think that the default should probably use utf8. I'll come up with a clearer plan once I get to it.

**Comment by Keats** [comment]
Syntax wise, we could use the same stuff as the regex crate, a few examples:
```
[[:alnum:]]    alphanumeric ([0-9A-Za-z])
[[:alpha:]]    alphabetic ([A-Za-z])
[[:ascii:]]    ASCII ([\x00-\x7F])
[[:word:]]     word characters ([0-9A-Za-z_])
```

**Comment by Keats** [comment]
@dragostis are the hooks for that in place in the `procedural` branch? I can get started if so

**Comment by dragostis** [comment]
@Keats The predefined rules can be added in the [generator](https://github.com/pest-parser/pest/blob/procedural/pest_derive/src/generator.rs#L16) and they should also be added in the [validator](https://github.com/pest-parser/pest/blob/procedural/pest_derive/src/validator.rs#L82).

We should also decide what the final syntax will be and whether these rules can be redefined by the user. I like the regex crate approach, but I wouldn't mind a tad simpler syntax. In the case when we add extra syntax, this will need to be added to the parser.

**Comment by Keats** [comment]
How about `_alnum_`, `_ascii_`, etc?

**Comment by dragostis** [comment]
I'm thinking maybe we should use allcaps? `ALNUM`, `ASCII`. Maybe we can rename `comment` and `whitespace` to allcaps as well so signify the fact that they are defaults.

**Comment by Keats** [comment]
all caps could work but it's a bit loud visually

**Comment by dragostis** [comment]
I agree. I think, however, that it would be advantageous for these rules to qualify as Rust identifiers since they generate functions with the same names.

The underscore approach could work with the only drawback being that the underscore formatting is usually used in the case of unused variables.

**Comment by Keats** [comment]
maybe we can implement them and bikeshed on the name on the PR?

**Comment by dragostis** [comment]
@Keats I agree.

**Comment by Keats** [comment]
So i've made a macro to generate the predefined inputs like:
```rust
macro_rules! add_builtin {
    ($predefined: expr, $name: ident, $pattern: expr) => {
        $predefined.insert(stringify!($name), quote! {
            fn $name<I: pest::inputs::Input>(
                pos: pest::inputs::Position<I>,
                _: &mut pest::ParserState<Rule, I>
            ) -> Result<pest::inputs::Position<I>, pest::inputs::Position<I>> {
                $pattern
            }
        });
    };
}
```

that can be used like:
```rust
    add_builtin!(predefined, any, pos.skip(1));
    add_builtin!(predefined, eoi, pos.at_end());
    add_builtin!(predefined, soi, pos.at_start());
    add_builtin!(predefined, digit, pos.match_range('0'..'9'));
```

But how should things like `{ uint ~ ['.'] ~ digit* ~ ( exp ~ ( uint | sint ))? }` be handled? `and_then` for `~` but not too sure about the others

**Comment by dragostis** [comment]
You can use multiline `{}` blocks.

**Comment by Keats** [comment]
I meant more on what code pest is generating for `*`, `?` etc but I guess I can just put it in a .pest file and see what gets generated...

**Comment by dragostis** [comment]
@Keats Oh, there's no need for that. There's good documentation for `inputs::Position` and `ParserState` and also a [JSON example](https://github.com/pest-parser/pest/blob/procedural/pest/tests/json.rs#L39).

**Comment by Keats** [comment]
I have a start [here](https://github.com/Keats/pest/commit/5f4611f386bbd75b29ddd9a632df4b91d14abd5f) that doesn't compile but I don't think I will have time to work on it anytime soon, putting it there in case someone wants to work on it

**Comment by dragostis** [comment]
@Keats Thank you so much for the work. I'll work on it from there and mention in a PR.

**Comment by jstnlef** [comment]
I'm curious how this is going. I wouldn't mind picking it up. I actually like the idea of all-caps for the built-in rules. It's quite common to see lexical rules in grammar files with all-caps names. Just look at any ANTLR grammar.

**Comment by jstnlef** [comment]
Added a number of basic types. These are all subject to change before the 2.0 release but have been implementing so I'm closing this.
