### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by jrmuizel** [pest-parser/pest#110]
Both http://dragostis.github.io/pest/pest/ (from crates.io) and http://pest-parser.github.io/pest/pest (from Readme.md) give 404s

**Comment by dragostis** [comment]
I'm pushing a fix for the README right now, but the link on creates.io will have to stay as it is until a new version of pest is pushed, since pushing a new version just to change the link is counterproductive for people maintaining projects that use pest.
