### ISSUE TITLE
Rule matching a single character causes error

### ISSUE THREAD

**Issue by turboladen** [pest-parser/pest#120]
This may just be user error, but I couldn't figure out how to resolve based on anything in docs or tests. I'm trying to build a grammar that, amongst other things, specifies a rule that matches a single character. After commenting out lines of my original grammar, I narrowed the failure down to this:

```rust
// src/lib.rs

#[macro_use]
extern crate pest;

use pest::prelude::*;

impl_rdp! {
    grammar! {
        kilo { ["k"] }
    }
}
```

Results:

```
pest_test git:master ❯ cargo check
   Compiling pest_test v0.1.0 (file:///private/tmp/pest_test)
error: no rules expected the token `filter`
  --> src/lib.rs:6:1
   |
6  | / impl_rdp! {
7  | |     grammar! {
8  | |         kilo { ["x"] }
9  | |     }
10 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate

error: Could not compile `pest_test`.

```

```
pest_test git:master ❯ rustc --version
rustc 1.19.0 (0ade33941 2017-07-17)
```

**Comment by turboladen** [comment]
FWIW, same behavior with the latest nightly:

```
pest_test git:master ❯ rustc --version
rustc 1.21.0-nightly (df511d554 2017-08-14)
```

**Comment by dragostis** [comment]
You're missing the assignment.

```
kilo = { ["k"] }
```

However, pest 1.0 has just today hit beta and it makes using the actual grammar much easier.

**Comment by turboladen** [comment]
🤦‍♂️ My brain must be thinking in day-job-Ruby blocks. Thanks, I'll give the beta a try!
