### ISSUE TITLE
Add tutorial

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#123]
The tutorial should probably tackle the issue of writing a JSON parser that also makes a simple AST.

**Comment by Techcable** [comment]
It'd be very nice if it also included information on how to use the precedence climbing features, as I had to resort to hand-rolling my own recursive descent parser as there aren't even any examples on it.

**Comment by dragostis** [comment]
@Techable That's really unfortunate. There is a calculator test in pest/tests, but it uses a manually written parser. However, the grammar is something similar to `term ~ (op ~term)*`, where `op` includes all operators, regardless of precedence.

**Comment by jstnlef** [comment]
Closing here this since this will be put into the book.
