### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#126]
Some slowdown can be noticed when parsing due to the new `Position` API. I have not yet identified the source of the problem. Minor testing shows the `Position` API to be as fast or even faster than manual parsing, however, full examples appear to be slower.

Possible causes:
* cache miss when [indexing](https://github.com/pest-parser/pest/blob/master/pest/src/parser_state.rs#L139) the queue
* use of `Rc`s, but I doubt it
* [tracking](https://github.com/pest-parser/pest/blob/master/pest/src/parser_state.rs#L153)

**Comment by Keats** [comment]
Do you have benchmarks for lexing/parsing for current pest and pest v1?

**Comment by dragostis** [comment]
@Keats There is the json example in pest/benches. You can compare it with 0.4 if you remove the `consume` call:

```
JsonParser::parse_str(Rule::json, &data).unwrap()
```

**Comment by dragostis** [comment]
The performance issue has been mitigated. I'm going to leave the issue open until we have some proper benchmarking.

**Comment by dragostis** [comment]
Added [benchmarks](https://github.com/pest-parser/pest#sheer-performance).
