### ISSUE TITLE
Panic overflow on derive(Parser)

### ISSUE THREAD

**Issue by olivren** [pest-parser/pest#128]
When trying to parse an empty .pest file, the derive macro panics due to an overflow. I would expect one of these two results:

1. A panic with a meaningful error message
2. A success that produces an empty grammar (a Parser that matches nothing)

I found this bug because I was setting up a new project using pest, and just wanted to be sure that the basic structure of my code was ok. In particular, I created an empty .pest file because I didn't want to start writing a grammar until my project was correctly setup. I copy/pasted an example from the doc, instead.

```
error: proc-macro derive panicked
 --> src\parser\mod.rs:5:10
  |
5 | #[derive(Parser)]
  |          ^^^^^^
  |
  = help: message: attempt to subtract with overflow
```

**Comment by dragostis** [comment]
Nice find! Fixing it right now. #129 is already fixed. I will push the changes and launch `beta.4 in a bit.
