### ISSUE TITLE
Make the brackets optional for `tokens` in `parses_to!`

### ISSUE THREAD

**Issue by olivren** [pest-parser/pest#130]
In the `parses_to!` macro, the expected result is given after the `tokens:` keyword, and the result itself is inside square brackets `[ ... ]`.

The brackets imply that there can be multiple top-level tokens, but I don't see how that would be possible. In my mind, if `rule` is `Rule::my_rule`, then `tokens` will always be of the form `[my_rule(x, y, ... )]`

```rust
parses_to! {
    parser: Parser,
    input:  "hello",
    rule:   Rule::my_rule,
    tokens: [my_rule(0,5)]
}
```

If this is true, I think it makes sense to allow (or even to force) removing the brackets.

```rust
parses_to! {
    parser: Parser,
    input:  "hello",
    rule:   Rule::my_rule,
    tokens: my_rule(0,5)
}
```

**Comment by dragostis** [comment]
That is not always the case. If `my_rule` from your example is silent like this:

```
my_rule = _{ subrule* }
```

then the top level element will be a list of multiple `subrule`s.

**Comment by olivren** [comment]
Ok, thanks for clearing that up!
