### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by olivren** [pest-parser/pest#132]
I wrote a grammar for the Java Properties file format, and all the rules work perfectly... except for the top level rule.

Running the top level rule results in `fatal runtime error: out of memory`, after the process consumed 6 GB of memory. This is true on any input, even on an empty string.

The grammar:

```
newline = _{ "\n" | "\r\n" | "\r" }
newline_char = _{ "\n" | "\r" }

space = _{ " " | "\t" | "\x0c" }

xdigit = _{ 'a'..'f' | 'A'..'F' | '0'..'9' }

end_of_line = _{ (newline | eoi) }

////////

logical_line_split = _{ "\\" ~ newline ~ space* }

unicode_escape = @{ "\\u" ~ xdigit ~ xdigit ~ xdigit ~ xdigit }
ascii_escape = @{ "\\" ~ !("u" | newline_char) ~ any }

key_chars = @{ (!(":" | "=" | "\\" | space | newline_char) ~ any)+ }
value_chars = @{ (!("\\" | newline_char) ~ any)+ }

key_component = _{ key_chars | ascii_escape | unicode_escape }
value_component = _{ value_chars | ascii_escape | unicode_escape }

key = { key_component ~ (logical_line_split* ~ key_component)* }
value = { (logical_line_split* ~ value_component)* }

spaces_or_splits = _{ (space | logical_line_split)* }
key_value_line = { spaces_or_splits ~
                   key ~
                   spaces_or_splits ~
                   ("=" | ":")? ~
                   spaces_or_splits ~
                   value ~
                   end_of_line
                 }

////////

blank_line = { space* ~ end_of_line }
comment_line = { space* ~ ("#" | "!") ~ (!newline_char ~ any)* ~ end_of_line }

////////

file = { soi ~ (blank_line | comment_line | key_value_line)* ~ eoi }
```

The test:

```
#[test]
fn file_t() {
    parses_to! {
        parser: Props,
        input: "",
        rule:   Rule::file,
        tokens: [file(0,0)]
    }
}
```

Again, all the other rules that produce an AST node are unit tested, and they run correctly and quickly. Only the top level has this problem.

I'm using Windows 7, rustc 1.19, pest 1.0.0-beta.4, and I tried in both release and debug.

**Comment by olivren** [comment]
I suspect the problem comes from trying to match `eoi` multiple times: once in `end_of_line`, and once in `file`. If I remove `eoi` from `end_of_line` I don't get an out of memory anymore (not a solution, because then the grammar becomes wrong).

**Comment by dragostis** [comment]
If `end_of_line` matches at `eoi`, it will match infinitely in your example, because it's in a repetition expression in the `file` rule. Your `blank_line` definition will match the empty string, which is not a blank line, so maybe it should be redefined?

**Comment by dragostis** [comment]
Also, you're welcome to join our [Gitter](https://gitter.im/pest-parser/pest) for questions and discussion. 😃

**Comment by dragostis** [comment]
A simple solution to the problem I've illustrated would be to fail `blank_line` if `eoi` has been reached:

```rust
blank_line = { !eoi ~ space* ~ end_of_line }
```

**Comment by olivren** [comment]
The solution works like a charm. My grammar is fully complete now, thanks.

Do you think it would be possible to prevent the Out of memory error, by detecting that the same rule is being called over and over without making any progress?

**Comment by dragostis** [comment]
@olivren That's a good idea. I'll close this issue and open a new one about that.

**Comment by dragostis** [comment]
I've opened two issues. Detecting this at runtime is a no-go since it would hinder performance, but it's possible to detect it statically at compile-time.

How was the experience? Any ideas on how to improve the library?

**Comment by olivren** [comment]
I just logged into gitter, I can talk about my experience there.

**Comment by olivren** [comment]
Oh and detecting the infinite loop at compile time would be awesome. If it's not possible, please consider detecting it at runtime at least in debug mode.
