### ISSUE TITLE
Lifetime issue with span.as_str()

### ISSUE THREAD

**Issue by sunng87** [pest-parser/pest#141]
I have a function that takes a `&str` and I would like to get a vector of parsed str segments, say `Vec<&str>`. 

I'm using pest parser API `parse_str` to get `Pairs`, convert it to `FlatPairs` and filter those rules to get ones I'm interested in. To get the actual string slice, I convert `Pair` to `Span` by `into_span()` and then push `span.as_str()` to the output vector.

The issue is `&str` generated from `span.as_str()` cannot live out of the scope of `span`.  So it's impossible to be returned from the function. 

From my understanding, `as_str()` should return a slice that shares same lifetime with the `&str` passed into `parsed_str`. However, it has the same lifetime with `Span` currently.

(For now we can use the start/end position to get slice from original `&str` though)

**Comment by dragostis** [comment]
`Span` currently holds an `Rc<Input>`. This level of indirection causes the lifetime issue mentioned.

The reason why lifetimes weren't used is because they made the API quite complicated and I'm not quite sure whether there is a better solution.

In this particular case it might be worth returning a `Vec<Span<I>>`.

**Comment by dragostis** [comment]
Also, `parse_str` is pretty good for debugging, but I wouldn't recommend using it in production, since is reallocated the the `&str` into a `String`.

**Comment by sunng87** [comment]
I see. But `StringInput` only accepts `String` so I will have to `to_owned` too

**Comment by sunng87** [comment]
@dragostis I was trying to change `StringInput` to hold a borrowed `&str` instead of `String`. Everything seems work except the `FileInput`. 

If we want to keep the `FileInput` API, we have to owner the file content and maintain a reference to inself:

```
struct FileInput<'a> {
  content: String, // file content
  file_name: OsString,
  input: StringInput<'a> // the input actually hold a reference to the struct itself
}

Unfortunately, [rust doesn't seem to support self referencing at the moment ](https://internals.rust-lang.org/t/improving-self-referential-structs/4808).

I'll look into other approaches. 
```

**Comment by dragostis** [comment]
I guess `StringInput` should work with both `&str` and `String` (probably a `Cow`), but I think it's fine if `FileInput` stays as is.

**Comment by sunng87** [comment]
A `Cow` would work for this. I'll make a pull request later.

**Comment by dragostis** [comment]
I'm pulling this out of the 1.0 milestone for now.
