### ISSUE TITLE
Modifier non-atomic (!) doesn't work

### ISSUE THREAD

**Issue by iology** [pest-parser/pest#142]
https://docs.rs/pest_derive/1.0.0-beta.5/pest_derive/#Grammar

```
// start from c
c = @{ b }
b = !{ a ~ "b" }
a =  { "a" }
```

produces `c()`, not `c(b(a()))`.

**Comment by iology** [comment]
Thanks for the fix. Now the result for input "ab" is c(a()), not c(b(a())) in the doc, is it intended behavior?

**Comment by dragostis** [comment]
That is intended behavior since `b` is inside an atomic rule. I'll fix the docs too.
