### ISSUE TITLE
FlatPairs panic in iteration

### ISSUE THREAD

**Issue by sunng87** [pest-parser/pest#144]
Hi @dragostis, I'm getting this panic when iterating over `FlatPairs`. It seems we have some index overflow.

> thread 'template::test_parse_template' panicked at 'index out of bounds: the len is 76 but the index is 76', /checkout/src/liballoc/vec.rs:1555:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at /checkout/src/libcore/panicking.rs:58
  10: <alloc::vec::Vec<T> as core::ops::index::Index<usize>>::index
             at /checkout/src/liballoc/vec.rs:1555
  11: <pest::iterators::flat_pairs::FlatPairs<R, I>>::is_start
             at /home/nsun/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.0-beta.6/src/iterators/flat_pairs.rs:87
  12: <pest::iterators::flat_pairs::FlatPairs<R, I>>::next_start
             at /home/nsun/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.0-beta.6/src/iterators/flat_pairs.rs:77
  13: <pest::iterators::flat_pairs::FlatPairs<R, I> as core::iter::iterator::Iterator>::next
             at /home/nsun/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.0-beta.6/src/iterators/flat_pairs.rs:108
  14: handlebars::template::test_parse_template
             at src/template.rs:694
  15: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1480
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/libtest/lib.rs:141
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99

Reproducible case can be found at https://github.com/sunng87/handlebars-rust/pull/177 

Run `RUST_BACKTRACE=1 cargo test template::test_parse_template` on that branch and you can see it.

**Comment by dragostis** [comment]
I'm traveling right now, but I'll take a look over it as soon as I can.
