### ISSUE TITLE
Match exception: available?

### ISSUE THREAD

**Issue by Songbird0** [pest-parser/pest#154]
Hi!

Does the pest parser support match exception `[^abc]` ? I haven't found an example about it in [`pest_derive` documentation](https://docs.rs/pest_derive/1.0.0-beta.9/pest_derive/#modifiers).

I would wish to build a rule like this (pseudo pest code): `foo = { "*"+ ~ (^*) }`

You should read: *matches one or more `*` characters followed by something that is **not** a `*` character*.

Raw regex: `\*+[^*]`

**Comment by dragostis** [comment]
No, there is currently no syntax for this, but `[^abc]` is easily replaceable with `!("a" | "b" | "c") ~ any`. It's pretty hard to decide whether adding specific syntax helps or not, i.e. whether it would be more confusing to have this extra syntax to overwhelm you or to lack this particular handy thing from regex.

Your particular example could be written as `"*"+ ~ !"*" ~ any`.

**Comment by Songbird0** [comment]
Oh, ok, I didn't understand. Thanks!

Maybe should you add an example in the pest_derive doc? I can do it if you're busy.

**Comment by dragostis** [comment]
I guess this has a better place in the [pest book](https://github.com/pest-parser/book) that I'm currently working on.

**Comment by Songbird0** [comment]
Cool! I'm watching it. :)
