### ISSUE TITLE
Consider adding support for regex style fixed min/max repetition expression

### ISSUE THREAD

**Issue by negator** [pest-parser/pest#156]
The ability to specify repetition counts is useful when parsing things like sha hashes and urls. It would be nice there was support for min/max limits, something like the following:
```
repeat = {  "a"{1, 5} ~ "b" }  // Indicates "a" can repeat no less than once and no more than 5

``` 

 The only workaround currently, appears to be to create intermediate atomic rules with repeating optional tokens (which is clearly less performant):

```
arule = @{ "a" ~ "a"? ~ "a"? ~ "a"? ~ "a"? }
```

**Comment by dragostis** [comment]
I agree. The reason I didn't add this yet is because I'm not yet sure about the syntax. But this would be a nice thing to have before 1.0 launches.
