### ISSUE TITLE
How to parse whitespace sensitive languages?

### ISSUE THREAD

**Issue by Boscop** [pest-parser/pest#168]
[This parser](https://github.com/Keats/tera/blob/master/src/parser.rs#L232-L234) only uses explicit whitespace after logical operators, does that mean all other whitespace is implicitly consumed and thrown away by pest? How can it be disabled and whitespace be parsed explicitly so that line indentation (tabs) and alignment (spaces) information can be used?

**Comment by dragostis** [comment]
If you want to parse whitespace manually, you can do so by simply not defining the `whitespace` rule. However, whitespace handling can be changed with the help of atomicity. Rules can be either `@`, `$`, or `!`, depending on your needs. The first two create a cascading effect of banning automatic whitespace handling, while the last one cancels this effect.

**Comment by Boscop** [comment]
Thanks, where are @, $, and ! documented? I read the pest book but it didn't explain their difference.

**Comment by dragostis** [comment]
Unfortunately, I haven't had time lately to work on the book, but the reference on docs.rs is completely documented. You can find the info [here](https://docs.rs/pest_derive/1.0.0-beta.16/pest_derive/#modifiers).

**Comment by dragostis** [comment]
I'm closing this for now. Feel free to reopen if you have any other questions.
