### ISSUE TITLE
Improve compilation times

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#169]
Compilation times should be as small as possible. Benchmarking should help reach this goal.

**Comment by Nadrieril** [comment]
Caching results between compilations would help enormously with compilation times. Do you know if it's possible ?

**Comment by CAD97** [comment]
In theory rustc itself shouldn't be recompiling the macro at all if you aren't touching that file (and stay on the same toolchain). In reality it's pretty complicated.

TBH, I'd be fairly suspect of any attempt to add incrementality on the level of an individual procedural macro, especially one that works with input as "small" as pest's without a good benchmark to back it up and a good battery to show it doesn't mess up.

Everything is theoretically possible (after all, Rust is Turing Complete and a proc macro is "just" Rust code), but how well it'd work is an open question. It'd still involve reading the `.pest` to check for changes and read/writing a new cache file, so I'm unconvinced it'd help much for how little work pest really needs to be doing.

That said, benchmarks beat my theories hands down.

**Comment by Nadrieril** [comment]
Well, right now I moved the parser into its own crate because compilation was horribly slow, and that works for caching as long as I don't change anything. When I do it takes ~5s to compile just that crate, if that counts as benchmark.
Looking at pest_bootstrap, it looks like I could just invoque the macro myself in build.rs and store the result in a file. I'll try to see if that helps cargo figure things out.

**Comment by PSeitz** [comment]
The bad compile times come from `pest_derive`, when I extract the generated code with cargo expand and remove the `pest_derive`  dependency, the compile times go down from 15.3s to 3.2s

Measuref with hyperfine
`hyperfine 'cargo clean; cargo build --release'`

This project which uses an older version of pest without `pest_derive` has also faster compile times (3.7s)
https://github.com/Keats/graphql-parser

Are macros equivalents of `impl_rdp!` and `grammar!` still available in newer version?

**Comment by CAD97** [comment]
You may be interested in using [profile overrides](https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#overrides) to lower pest-derive's optimization level if you're concerned about clean build performance.

To be completely honest, though, I'm more interested in focusing on compile time impact on the invoking crate than that of the derive crate itself. Any rebuild should probably have the derive crate cached, and in the near-ish future we should be able to use watt (or a similar runtime) to distribute the proc macro precompiled to wasm. (The difficult part for pest is that it wants to read external files; we either need to add a sidechannel to watt to pass the contents of the file or use a wasi-aware runtime.)

**Comment by dragostis** [comment]
@CAD97, watt would be a great addition, indeed!

**Comment by tomtau** [comment]
Are the compilation times still a concern? rustc has improved a lot since 2017, so I'll close this issue, but feel free to reopen it.
