### ISSUE TITLE
Atom/IntelliJ pest plugin

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#174]

**Comment by miqh** [comment]
@dragostis, could you please clarify what's needed of these plugins?

If it's just providing grammar scopes to enable syntax highlighting of `.pest` files, I'm happy to try do up a basic Atom one.

**Comment by dragostis** [comment]
@miqh, syntax highlighting is the idea, yes. I don't think there's much need for more for now. Grammars are going to be parametrizable soon and maybe there's worth do do more. Maybe we could even use WebAssembly for this? (`meta` and `vm` could be of help)

**Comment by ice1000** [comment]
FYI IntelliJ plugin: https://github.com/pest-parser/intellij-pest

**Comment by dragostis** [comment]
@ice1000, thanks a lot for the awesome work!

**Comment by ice1000** [comment]
I wonder if #381 can be a `bin`. My plugin can ask you to install it, configure it in the plugin and I can provide on-the-fly syntax highlighting tools, for instance (I'm just throwing some random thoughts here, don't be too serious :sweat_smile:) I can introduce a kind of comment like this:

```c
//#FFFF00
name = { ASCII_LETTER+ }

equation = { name ~ "=" ~ name }
```

and you can click some button to raise a text window, type some codes and my plugin invokes the bin as a background process (that can be a vm-based one) continuously dump the syntax info json to the IDE and the IDE highlights the code in the text window, just like the showcase on pest.rs does.
