### ISSUE TITLE
Unmatched expressions modify the stack

### ISSUE THREAD

**Issue by jturner314** [pest-parser/pest#176]
While working with `pest`, I discovered that expressions that aren't matched still can modify the stack with `push` or `pop`, which seems like a bug. Consider:

`grammar.pest`
```rust
foo = ${ soi ~ push("") ~ (aba | a) ~ eoi }
a = @{ peek ~ "a" }
aba = @{ push("a") ~ "b" ~ pop }
```

`main.rs`
```rust
#[macro_use]
extern crate pest_derive;
extern crate pest;

use pest::Parser;

#[cfg(debug_assertions)]
const _GRAMMAR: &'static str = include_str!("grammar.pest");

#[derive(Parser)]
#[grammar = "grammar.pest"]
pub struct MyParser;

fn parse_string(s: &str) {
    match MyParser::parse_str(Rule::foo, s) {
        Ok(o) => println!("ok: {:?}", o),
        Err(e) => println!("err: {}", e),
    }
}

fn main() {
    parse_string("a");
    parse_string("aa");
}
```
The output when running this is
```
err:  --> 1:1
  |
1 | a
  | ^---
  |
  = expected foo
ok: Pairs { pairs: [Pair { rule: foo, span: Span { start: 0, end: 2 }, inner: Pairs { pairs: [Pair { rule: a, span: Span { start: 0, end: 2 }, inner: Pairs { pairs: [] } }] } }] }
```

I would expect The string `"a"` to parse correctly, and the string `"aa"` to fail parsing, but the parser does the opposite. What I think happens is this:

1. Starting with the `foo` rule, `soi ~ push("")` matches, so the stack is now `[""]`.
2. The next step is `~ (aba | a)`, so the parser tries rule `aba` first.
3. The parser sees that `push("a")` matches, so the stack is now `["", "a"]`.
4. The parser sees that `~ "b"` doesn't match, so `aba` doesn't match, so it goes back up to `~ (aba | a)` and tries `a` next. Note that even though `aba` didn't match, it modified the stack.
5. We're in rule `a` now. Since the top of the stack is `"a"`, `peek ~ "a"` can only match the string `"aa"`, not `"a"`.
6. In the `"aa"` example, the final part is `~ eoi`, which matches.

The surprising part is that even though `aba` didn't match, it still modified the stack. This seems like a bug. I would expect the stack to be left unmodified by expressions that don't match (i.e. restore the stack after the expression fails to match).

In addition to `(aba | a)`, `aba` in other expressions exhibits the same behavior, such as `(aba? ~ a)` and `(!aba ~ a)`.

Assuming this is a bug, here are a couple of strategies to fix this:

1. One solution is to clone the stack at the beginning of each expression in a branch (`expr?`, `expr1 | expr2`, etc.) or `!expr` in the parser, and then if the expression fails to match, restore the stack from the clone. I wouldn't expect the clone to be very expensive because the stack only contains `Span` items (which are small), unless you're parsing a very deeply nested document which builds a large stack.

2. Instead of cloning, another solution is to use a [persistent](https://en.wikipedia.org/wiki/Persistent_data_structure) [stack](http://www.toves.org/books/persist/) that makes it possible to store past versions of the stack without cloning the whole thing. This is often implemented as a singly linked list, which comes with its own issues but would work.

If the existing behavior is intentional, it should be better documented, and I would consider adding `push_maybe` and `pop_maybe` commands that only modify the stack if the expressions containing them match.

I can spend some time on a fix or better documentation.

**Comment by dragostis** [comment]
I completely agree with you on the proposed behavior. On a first glance, it might seem better to go for the cloning implementation, since this stack is not designed to be large. However, the resulting performance penalty will probably be hard to debug if met. The persistent stack implementation should be able to mitigate this corner case.

**Comment by jturner314** [comment]
Okay, I'll work on the cloning approach. At first glance, it looks fairly straightforward to implement, but it may take me a while because I'm unfamiliar with the `pest_derive` codebase.

If the many small heap allocations (due to cloning) become an issue for small stacks, one idea is to change the stack from `Vec<Span<I>>` to

```rust
enum Stack {
    Array([Span<I>; 8]),
    Vector(Vec<Span<I>>),
}
```

where `8` is a tunable parameter (possibly even user-tunable with an attribute on the parser type). This way, as long as the stack stays 8 elements or less, there aren't any heap allocations. This optimization doesn't help large stacks, but might help for the common case (small stacks).

However, I think it makes the most sense just to keep the stack as `Vec<Span<I>>` unless it becomes a performance issue.

**Comment by dragostis** [comment]
@jturner314 Any updates on the issue? I still consider the persistent stack a good approach.

**Comment by jturner314** [comment]
I'm really sorry about the delay. I put together an initial implementation using strategy 1 (cloning and restoring the stack). You can see it at [jturner314/pest/fix-unmatched-stack-ops](https://github.com/pest-parser/pest/compare/master...jturner314:fix-unmatched-stack-ops). I still need to update a couple of the existing tests and add more tests to make sure the implementation is correct.

There are a few additional things on that branch:

* Add documentation for the variants of `pest_derive::ast::Expr`. (Btw, did you know that you can view documentation for private items with `cargo rustdoc --open -- --document-private-items`? I just learned this recently, and it's very helpful when working on an unfamiliar codebase.)
* Add a predefined `drop` rule which unconditionally drops the top of the stack without trying to match it. (This is necessary because, AFAICT, with the new stack behavior it's not possible to achieve the `drop` behavior with a combination of existing expressions.)
* I changed `loop` statements to `while let` statements because this makes them more concise and IMO easier to read.

Note that in the implementation, if the result of parsing an expression is `Err(_)`, the stack might still be modified. This makes it possible to avoid a few extra clones of the stack, and this behavior isn't exposed in the public API because client code doesn't have access to the `ParserState` instance.

I did have a question for you regarding the behavior: should `&e` be able to modify the stack if it matches? I lean towards "yes", but it's a little weird because `&e` matches without making progress.

If cloning the stack on every branch turns out to be too expensive, I had a couple more ideas:

3. Change the stack to `Rc<Vec<Span<I>>` to make the cloning on each branch very cheap (just increment the reference count). In this case, the contents of the stack would need to be cloned only when the stack is actually modified with `push`/`pop`/`drop` calls, which probably occur less frequently than branching expressions.
4. Remove the `stack` field from `ParserState`; the state of the stack will be handled on the call stack. Pass the stack to subexpression parsers as `&'a [Span<I>]`, then the subexpression parser would evaluate to a value of type `Result<(Position<I>, Cow<'a, [Span<I>]>), Position<I>)>`, where `Cow<'a, [Span<I>]>` is the new stack (`Cow::Borrowed` if it was not modified, `Cow::Owned` if it was). Conceptually, it seems simpler to handle the stack on the call stack like this than to keep it in `ParserState`. However, I expect that changing to this implementation would be more complex.

What do you think so far?

**Comment by dragostis** [comment]
> * Add documentation for the variants of pest_derive::ast::Expr. (Btw, did you know that you can view documentation for private items with cargo rustdoc --open -- --document-private-items? I just learned this recently, and it's very helpful when working on an unfamiliar codebase.)

This is awesome. Definitely something that I intended to do, but had a lot of pressure to try and release 1.0.
 > * Add a predefined drop rule which unconditionally drops the top of the stack without trying to match it. (This is necessary because, AFAICT, with the new stack behavior it's not possible to achieve the drop behavior with a combination of existing expressions.)

To improve expressiveness, one might also add a `stack` rule that matches the whole stack. This should make for some interesting grammars. However, I still haven't thought enough about how to error report in these cases. Also, I believe that `drop` should probably not panic in case of en empty stack, but fail.

> I did have a question for you regarding the behavior: should `&e` be able to modify the stack if it matches? I lean towards "yes", but it's a little weird because `&e` matches without making progress.

I feel like having it modify the stack would be both more useful and natural.

> If cloning the stack on every branch turns out to be too expensive, I had a couple more ideas:
>
>  3. Change the stack to `Rc<Vec<Span<I>>` to make the cloning on each branch very cheap (just increment the reference count). In this case, the contents of the stack would need to be cloned only when the stack is actually modified with `push`/`pop`/`drop` calls, which probably occur less frequently than branching expressions.
>  4. Remove the `stack` field from `ParserState`; the state of the stack will be handled on the call stack. Pass the stack to subexpression parsers as `&'a [Span<I>]`, then the subexpression parser would evaluate to a value of type `Result<(Position<I>, Cow<'a, [Span<I>]>), Position<I>)>`, where `Cow<'a, [Span<I>]>` is the new stack (`Cow::Borrowed` if it was not modified, `Cow::Owned` if it was). Conceptually, it seems simpler to handle the stack on the call stack like this than to keep it in `ParserState`. However, I expect that changing to this implementation would be more complex.

It feel like any solution involving a `Vec` would be too slow. If the stack is too big, cloning will be too costly. A persistent stack/list should be fast enough in the usual case for this particular use case and it should make the implementation simpler?

> Edit: I just realized that the stack only needs to be cloned once for `Expr::Choice`, not for each alternative subexpression (the initial implementation), so that should help a lot. I don't think that's the case for `Expr::Rep`; for that case, the stack does need to be cloned on every subexpression repetition.

Isn't it the same with `Expr::Rep`? Once a repetition's subexpression matches, it cannot possibly go back. You can simply clone once and use that clone until the end of the repetition.

**Comment by jturner314** [comment]
> one might also add a `stack` rule that matches the whole stack.

This is a good idea and would help with a parser that I'm working on.

> Also, I believe that `drop` should probably not panic in case of en empty stack, but fail.

Yes, that's better. I made the change on [my branch](https://github.com/pest-parser/pest/compare/master...jturner314:fix-unmatched-stack-ops).

> It feel like any solution involving a `Vec` would be too slow. If the stack is too big, cloning will be too costly. A persistent stack/list should be fast enough in the usual case for this particular use case and it should make the implementation simpler?

I tend to agree regarding the performance. I wrote a simple singly-linked `Stack` type with reference-counted nodes based on [this example](http://cglab.ca/~abeinges/blah/too-many-lists/book/third-final.html) and changed the `ParserState.stack` from `Vec` to `Stack`. (See the [most recent commit](https://github.com/pest-parser/pest/commit/e1543a566ae2681eb0a1053262a3ff199834d549).) With the new `Stack` type, all of the operations we need to do (`clone`, `peek`, `push`, `drop_top`) are cheap; they don't require cloning the contents of the stack.

Another idea to improve the performance somewhat is to set a flag on expressions when building/optimizing the AST to indicate whether any descendants of the expression can modify the stack (i.e. flag whether any descendants are `push`, `pop`, or `drop`). If an expression doesn't have any descendants that could modify the stack, then the code generator doesn't need to clone the stack. However, with the new `Stack` type, clones are cheap enough that this might not be worth the additional implementation complexity.

> Once a repetition's subexpression matches, it cannot possibly go back.

That is true. However, the stack needs to be cloned when both of the following conditions are true:

1. A subexpression can modify the stack and evaluate to `Err(_)`.
2. The parent expression can evaluate to `Ok(_)` when 1 happens.

> You can simply clone once and use that clone until the end of the repetition.

I guess it depends on the semantics you're trying to achieve. To me, repetition of `e` is equivalent to `e ~ e ~ ... ~ e` for an unknown number of `e`, where each `e` can modify the stack for the subsequent `e`. This meets both of the conditions: (1) the final subexpression can modify the stack and evaluate to `Err(_)`, and (2) the parent expression will still return `Ok(_)`. (The final `e` will fail to match (indicating the end of the repetition), and it needs to restore the stack from just before trying to match the final `e`. So, you need to clone the stack before trying each `e` because you don't which will be the final one.)

Here's an example parser to illustrate this:

```rust
rule = soi ~ (push('a'..'c') ~ ",")* ~ pop ~ pop ~ pop ~ eoi
```

It should match the following input:

```
a,b,c,cba
```

The first repetition of the parenthesized expression matches `"a,"`, resulting in the stack `["a"]`. The second repetition matches `"b,"`, resulting in stack `["a", "b"]`. The third repetition matches `"c,"`, resulting in stack `["a", "b", "c"]`. The parser will try to match the parenthesized expression a final time (pushing another `"c"` to the stack) and fail to match (because of the `","`), indicating the end of the repetition. If it had cloned the stack at the start of the repetitions, it would have saved stack `[]`. The correct stack after the repetitions is `["a", "b", "c"]`. Therefore, it must save the stack just before trying to match the final parenthesized expression.

By the way, I was wrong regarding `Expr::Choice`; the stack still needs to be cloned for each subexpression due to Rust's ownership rules. (You have to restore the saved stack before trying to match each subexpression. When you restore a saved stack by assigning it to `state.stack`, you lose ownership of the saved stack.)

I still need to work on testing. Otherwise, what are your thoughts?

**Comment by dragostis** [comment]
> I tend to agree regarding the performance. I wrote a simple singly-linked `Stack` type with reference-counted nodes based on [this example](http://cglab.ca/~abeinges/blah/too-many-lists/book/third-final.html) and changed `ParserState.stack` from `Vec` to `Stack`. (See the [most recent commit](https://github.com/pest-parser/pest/commit/e1543a566ae2681eb0a1053262a3ff199834d549).) With the new `Stack` type, all of the operations we need to do (`clone`, `peek`, `push`, `drop_top`) are cheap; they don't require cloning the contents of the stack.

The way I would imagine this to work is to have an API that knows how to revert in case a rule fails. This is how the current token queue works: when it starts parsing it remembers where the queue's last position was and pops everything out up to that position in case of `Err(_)`. Figuring out whether some sub-expression touches the stack will involve quite a bit of work, however, right now, I see no other way of making this work without negatively impacting performance.

I see how repetitions need cloning on every match and it makes sense.

**Comment by dragostis** [comment]
I have an idea on how to implement this elegantly. All that's needed is to have a specific `Stack` data structure that:

* uses a `Vec` to store all mutating operation that happened on it (`enum`)
* has a stack/`Vec` of positions that it can backtrack to by calling `truncate` on the above `Vec`; every backtrack pop the position
* a `Cache(&str, &str)` type of operation should be possible that increments the last backtracked position (so that it doesn't truncate the cache) which stores the top of the stack and the whole contents of the stack concatenated by folding over all the operations; the caching would only happen on `pop`, `peek`, and `stack` rules

Like this, truncating will effectively be a cheap comparison most of the time without actually costing a ton.

**Comment by jturner314** [comment]
> The way I would imagine this to work is to have an API that knows how to revert in case a rule fails. This is how the current token queue works: when it starts parsing it remembers where the queue's last position was and pops everything out up to that position in case of `Err(_)`.

I guess the primary question I have is (regardless of how the stack/snapshots are actually represented): "Who is responsible for snapshotting/restoring the stack?" I originally thought that I could modify the various methods on `ParserState` (e.g. `.sequence()`) to do this, but I realized that wouldn't work because the stack needs to be snapshotted within the closures that those methods call. My first implementation was to handle the snapshotting in the code generator simply because that was the most obvious way to do it. On further investigation, I think it might be possible to handle the snapshotting in `Position` by adding arguments to pass `&mut Stack` to the existing relevant methods (e.g. `.optional()`) and adding a couple of extra methods (e.g. `.choice()`).

It sounds like you'd prefer to handle the snapshotting in something like `Position` instead of the code generator. Is that correct?

> I have an idea on how to implement this elegantly. ...

Regarding the representation of the stack, it sounds like you're proposing to not represent the stack itself but rather a `Vec` of operations on the stack. Snapshots of the stack would be lengths of this `Vec`, so to restore to a previous state, you'd truncate the `Vec` to the snapshotted length. The only time you'd need to evaluate the operations (fold over the `Vec`) is when you actually need to know the contents of the stack (`pop`, `peek`, and `stack`). I think that approach will work. I don't know whether the linked-list stack or this `Vec<Operation>` approach would be faster; I'd have to benchmark to really know for sure. However, I suspect your proposed `Vec` approach would be faster because it wouldn't have to perform a separate allocation for each element, and to implement the `stack` rule it wouldn't have to follow pointers to traverse the linked list.

**Comment by dragostis** [comment]
I was thinking about the `Vec` design since it would match the current one and would be easy to implement. Truncation already happens [here](https://github.com/pest-parser/pest/blob/master/pest/src/parser_state.rs#L156) and [here](https://github.com/pest-parser/pest/blob/master/pest/src/parser_state.rs#L261), and this would use the same logic.

**Comment by jstnlef** [comment]
Hey there. @jturner314 I was wondering what the status of this is. If you'd like, I could try to take a stab at implementing the `Vec` design @dragostis mentioned. That is, of course, unless you're well on your way to finishing.

**Comment by jturner314** [comment]
@jstnlef That would be awesome if you could work on the implementation. I haven't really had a chance to work on this any more recently, and I probably won't for a while. If it helps, my latest work is on the [jturner314/fix-unmatched-stack-ops](https://github.com/jturner314/pest/commits/fix-unmatched-stack-ops) branch, but it uses a different approach (singly-linked stack).

**Comment by jstnlef** [comment]
@dragostis The stack rule you mentioned, that should probably drop the stack after it matches right?

**Comment by dragostis** [comment]
@jstnlef I don't think it should. Maybe there should be two rules, one that does and one that doesn't? BTW, in order for optimum performance, the strings should probably be saved in a `String`, but that means breaking compatibility which I don't really mind so much.

**Comment by jstnlef** [comment]
I can add a `stack_peek` and `stack_pop` and see what you think. I think I'll have a PR up at some point today. You can take a look and we can iterate from there.

**Comment by jstnlef** [comment]
@jturner314 If you try this with master branch I think you should see the behavior you're looking for ;)
