### ISSUE TITLE
Parsing user-defined operators with custom precedence / associativity

### ISSUE THREAD

**Issue by Boscop** [pest-parser/pest#186]
Is it possible to parse PureScript with a parser generator like pest?
Considering it allows user-defined operators with custom precedence / associativity (like haskell)..

[E.g.:](https://github.com/purescript/purescript-prelude/blob/v3.1.0/src/Data/Functor.purs#L27-L27)
```purescript
infixl 4 map as <$>
```

**Comment by dragostis** [comment]
The parser doesn't actually solve precedence itself, so, yes, you can. Precedence is solve with a `PrecClimber` data structure from the API that you can replace while processing your `Pair`s.

**Comment by Boscop** [comment]
When operator bindings can be defined after they are used in a source file (but should still apply), if I want to parse everything with default precedence/associativity first (into a flat array) and then when all possible operator bindings have been parsed, regroup all exprs into trees, is that a good approach to do with pest?

**Comment by dragostis** [comment]
I would say so, yes.

**Comment by dragostis** [comment]
I'm closing this issue. Feel free to open up for a broader discussion or maybe join our Gitter?
