### ISSUE TITLE
Example for how to handle left recursion?

### ISSUE THREAD

**Issue by Ophirr33** [pest-parser/pest#188]
For instance, with something like this:
```
alpha = { 'a'..'z' | 'A'..'Z' }
digit = { '0'..'9' }
id = @{ alpha ~ (alpha | digit | "_")* }
value = { (id | value ~ "." ~ id) }
```
value is left recursive, and and error is printed:
```
rule value is left-recursive (value -> value); pest::prec_climber might be useful in this case
```
As far as I can tell though, prec_climber lets you operate on Pairs after you've generated them. How would I rewrite the above grammar to let me then use the prec_climber api to fix it?

**Comment by dragostis** [comment]
You can simply define it like this:

```
value = { id ~ ("." ~ id)* }
```

**Comment by superblaubeere27** [comment]
And how to handle precedence? For example: `a + b * c` should be treated as `a + (b * c)`

**Comment by SkiFire13** [comment]
You can define multiple rules for that:

```
WHITESPACE = _{ " " }
atom = { 'a'..'z' }
mul = { atom ~ ("*" ~ atom)* }
add = { mul ~ ("+" ~ mul)* }
expr = { SOI ~ add ~ EOI }
```

You can also use the pairs api to feed a prec climber, as shown in https://github.com/pest-parser/pest/blob/master/pest/tests/calculator.rs#L190
