### ISSUE TITLE
Add optional filename to errors?

### ISSUE THREAD

**Issue by Keats** [pest-parser/pest#196]
The default error looks great but having it contain the filename would be even better imo, from `-->  10:31` to `--> ~/some_file.html:10:31`.
I can do that manually by replacing the string but that's not safe as I'm guessing the formatting might change in a minor version.

That would be a breaking change though.

**Comment by dragostis** [comment]
Errors should be extended for this use case. The functionality is present (to some degree) in the history of the `pest/src/error.rs` file.
