### ISSUE TITLE
Sharing rules between grammars?

### ISSUE THREAD

**Issue by waywardmonkeys** [pest-parser/pest#197]
I have a few grammars for related formats / languages that share some common rules. Is there a way to readily share rules between separate grammar files?

It wouldn't make sense to just have a single big grammar file.

In `nom`, I would be able to define new combinators that I'd use for things like basic types and such.

**Comment by dragostis** [comment]
Good point. There should be an import command in `.pest` files. This could be added in `1.1`. Let me know if you want to tackle it.

**Comment by waywardmonkeys** [comment]
Could you provide a couple of getting started pointers and I will see if I can tackle it?

**Comment by dragostis** [comment]
Of course. The necessary grammar should be [added to meta](https://github.com/pest-parser/pest/blob/master/meta/src/grammar.pest). Probably something like `use generic.pest` would do well.

Then this should be somehow integrated into the parser and validator in the `meta` crate. I'm not completely sure what the best approach would be in this case. My current hunch is to do the actual importing in [`parser::convert_rules`](https://github.com/pest-parser/pest/blob/master/meta/src/parser.rs#L101), where one could call parse and validate recursively, but this might not work and a change in architecture may be needed.
