### ISSUE TITLE
v1.0.5 includes a breaking change and should be reverted/yanked

### ISSUE THREAD

**Issue by SergioBenitez** [pest-parser/pest#198]
From my comment on https://github.com/pest-parser/pest/commit/1a13aac261999b16459f6896ad8c419966b13710:

> 1a13aac261999b16459f6896ad8c419966b13710 is breaking change because existing exhaustive matches on `Rule` will now fail to compile due to the new `eoi` variant. It should be reverted as soon as possible. v1.0.5 should be yanked as well.

**Comment by dragostis** [comment]
Crate yanked. I'll revert the commit as well.

**Comment by dragostis** [comment]
Done. Thanks a lot for the fast intervention and sorry for breaking the builds!
