### ISSUE TITLE
Need advice: speeding up the grammar

### ISSUE THREAD

**Issue by idubrov** [pest-parser/pest#201]
Is there any way to make the following grammar (it's reduced from the real grammar) :
```
expression     =  { "o" ~ ( "[" ~ expression ~ "]" )* }
```
faster on the following degenerate case:
```
let expr = "o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o[o";
```

As far as I understand, one possiblle solution could be to make "[" greedy, so parser never backtracks once "[" is matched.

?

**Comment by dragostis** [comment]
Are you having performance issues? Did you benchmark said case?

This particular case is not so obvious how to improve. One possible solution would be to unroll some of the recursive calls, but this would slow compilation dramatically. Another option would be to match closing and opening brackets without caring whether or not they match and then focus on that when you get back the token pairs.

**Comment by idubrov** [comment]
Yes, I did benchmark it. It seems like this case is exponential to the length of the chain.

Would it be possible to have "must match" marker? It seems to me that the parsing should be back to linear, if rules after "[" are marked by some sort of "must match" marker, something like this:
```
expression     =  { "o" ~ ( "[" ~ &( expression ~ "]" ) )* }
```

So, once parser fails to match (expression ~ "]"), it will immediately stop and report error that "expression" is expected (or "]").

**Comment by dragostis** [comment]
Oh, I see the problem now. This is easily fixable by not repeating repetition work, since PEGs are greedy by default. So, a recursive call doesn't make sense to be repeated:

```
expression = { "o" ("[" ~ expression ~ "]")? }
```

**Comment by idubrov** [comment]
Reason I'm repeating it is because I want it to be able parse a[1][2][3], too.

**Comment by dragostis** [comment]
I see. This is the perfect case where a Packrat parser makes sense. I'm wondering if such a case would be possible to find statically in order to optimize.

**Comment by dragostis** [comment]
Currently, you could first look for the expression, then match it:

```
expression     =  { "o" ~ &( "[" ~ expression ~ "]" ) ~ ( "[" ~ expression ~ "]" )* }
```

I'm not completely sure whether this mitigates all degenerate cases, though.
