### ISSUE TITLE
syn 0.12 / quote 0.4

### ISSUE THREAD

**Issue by ignatenkobrain** [pest-parser/pest#203]
We have updated syn/quote/synstructure recently in Fedora which broke pest... It would be very nice if you could update dependencies of pest_derive. Thank you in advance!

**Comment by dragostis** [comment]
Fixing this on `1.0.*` will be a tad involved. The plan was to have the new versions in `1.1`. Would that be okay? I backporting could also be an option, but it would be a lot of work.

**Comment by cuviper** [comment]
It should be fine for us to update Fedora to pest 1.1 too.
