### ISSUE TITLE
Owned variant of errors

### ISSUE THREAD

**Issue by remexre** [pest-parser/pest#204]
It'd be nice to have an owned Error type, when bubbling up errors is needed. Ideally, the owned version would have all the `&str`s in the Spans/Positions into shared `Arc<String>`s instead.

**Comment by dragostis** [comment]
It's hard to reason about this. The whole former API was based on `Rc`s and changing it to references was quite a hassle. Ideally, you should be able to easily have both cases, but this means duplicating pretty much the whole library, or using an awkward `Cow` everywhere which would both break the current API and be quite hard to use.

Do you have any high level use case for this?

**Comment by remexre** [comment]
I want to be able to put a pest error inside a failure, essentially. (And main isn't what owns the source code, but it is what's going to handle it)

**Comment by indeyets** [comment]
My use-case exactly. Tried to wrap pest's errors via failure_derive and figured out it won't be quite straight-forward
