### ISSUE TITLE
Avoid the include_str!("grammar.pest") hack

### ISSUE THREAD

**Issue by Michael-F-Bryan** [pest-parser/pest#207]
I was just skimming through the docs for `pest` and noticed it mentioning [a workaround] to make sure cargo re-runs the custom derive when your grammar gets updated.

Instead of this:

```rust
#[cfg(debug_assertions)]
const _GRAMMAR: &'static str = include_str!("path/to/my_grammar.pest"); // relative to this file

#[derive(Parser)]
#[grammar = "path/to/my_grammar.pest"] // relative to src
struct MyParser;
```

What if the custom derive automatically generated something like this:

```rust
impl MyParser {
  #[cfg(debug_assertions)]
  const GRAMMAR: &'static str = include_str!("path/to/my_grammar.pest"); 
}
```

I'm pretty sure associated constants are stable as of 1.23`, so this *should* be okay. As an added bonus, it also lets people see the raw grammar file when looking at the `MyParser` docs.

Thoughts?

[a workaround]: https://docs.rs/pest/1.0.6/pest/#pest-files

**Comment by dragostis** [comment]
This sounds like a nice idea and it's also backwards compatible.

**Comment by dragostis** [comment]
Unfortunately, I just remembered that this won't work. The issue is that `include_str!` works with paths relative to the current file compiled, which is something that, to my knowledge, you cannot access from a procedural macro in order to add to the `Parser` trait implementation automatically.
