### ISSUE TITLE
Int parse

### ISSUE THREAD

**Issue by sbant** [pest-parser/pest#221]
I have this grammar:
digit = _{ '0'..'9' }
int = @{ "-"? ~ digit+ }

when parse input:
let s = "10z";

Parser::parse(Rule::int, s);

It successful parsed as Text "10"

I think it should failed.

What can I do?

**Comment by dragostis** [comment]
Parsers don't need to parse the whole input. If you want to make sure you parsed the whole input, use the `eoi` (end-of-input) rule `digit = { '0'..'9' ~ eoi }`

**Comment by sbant** [comment]
sorry, but the real question is I want to parse "10z" to string.

grammar:
digit = _{ '0'..'9' }
int = @{ "-"? ~ digit+ }
float = @{ int ~ "." ~ digit+ }
number = @{ float | int }
expr = { number | var_name }
whitespace = _{ " " | "\t" | newline }
var_name = @{ (!var_exclude ~ any)+ }
var_exclude = { ":" | "=" | "," | ";" | "(" | ")" | op1 | whitespace }  // op1 is some other operator, like * / + -

if parse "10z" with:
Parser::parse(Rule::var_name , var_name );
it parsed to string "10z"

but parse with:
Parser::parse(Rule::int, expr);
it parsed to int 10

**Comment by dragostis** [comment]
It's hard to fully comprehend what the issue here is. Please follow up on [Gitter](https://gitter.im/dragostis/pest) for grammar-related questions.
