### ISSUE TITLE
Need advice on parsing comments

### ISSUE THREAD

**Issue by idubrov** [pest-parser/pest#225]
Is there any way to parse comments explicitly where necessary? For example, I want to handle comments just before the statement, like:
```
// comment should be handled explicitly
statement /* this one will be ignored */;
```
but ignore all the rest. Is my only option is to explicitly place rules for comments (let's say 'c' for comment and 'sc' for _silent_ comment) in all possible places?

**Comment by dragostis** [comment]
You could keep the current comment model for the ones you don't care about and match the ones that you do care about.

Another solution would be to make comments sub-rules, interesting ones non-silent, then filter out the false positives:

```
comment = _{ interesting | boring }
interesting = { ... }
boring = _{ ... }
```

**Comment by idubrov** [comment]
I wasn't specific enough -- the difference is not by the type of the comment, but rather by the location (in front of the "statement" is "interesting", anywhere else is "boring").

Also, if I make comment to produce rule, it seems like pest prefer to match comment at the end of the previous rule.

Ideally, I would like to do something like:
```
statement = { interesting_comment? ~ "statement" ~ ";"? }
```
But currently the comment will be matched by that time already by the "comment" rule.

**Comment by dragostis** [comment]
Of course. The key here is not bother so much since you can do it later. Make comments non-silent and filter out the interesting ones with the pairs API. (This might be hard since you can have comments basically everywhere)

Another solution would be to parse the input twice, looking for the interesting types of comments.

However, I advise you to make use of atomic rules. I.e. you could break everything into paragraphs which are atomic, then optionally match the interesting comment, then call a non-atomic paragraph parsing rule. Or any such combination.

**Comment by idubrov** [comment]
I'll try to play around and see if I can get some ergonomics in my grammar/parser. After all, maybe an explicit handling for comments would be even better in my case so I don't allow comments in places they will be "lost"?

Thanks. Awesome library, by the way, -- all of the sudden I found myself writing parsers one after another and I like `pest` very much!

**Comment by adeschamps** [comment]
@idubrov Here's an example where I kept track of the most recent comment when parsing a C-like grammar (here's the full [parser]):

```rust
let mut last_comment = None;
let mut structs = Vec::new();

for pair in pairs {
    match pair.as_rule() {
        Rule::comment => {
            last_comment = Some(parse_comment(pair));
        }
        Rule::struct => {
            structs.push(parse_struct(last_comment.take(), pair));
        }
    }
}
```

[parser]: https://github.com/adeschamps/lcm-rust/blob/cc7b464c79abf4395d4a03b50e1132dbb25612c5/lcm-gen/src/parser.rs#L23-L43
