### ISSUE TITLE
Tests compile slowly

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#234]
Recursive macros are notoriously slow to compile, and it seems that the `parses_to!` macro is no exception. A solution to this would be to have a function replace it, but since there is no nice way to define nested data structures without recursive macros, this might be quite a challenge to design.

**Comment by tomtau** [comment]
Are the test compilation times still a concern? rustc has improved a lot since 2018, so I'll close this issue, but feel free to reopen it.
