### ISSUE TITLE
Parse column bases data

### ISSUE THREAD

**Issue by ZockerRamires** [pest-parser/pest#239]
Hello all,

I’d like to build a grammar-file for parsing column bases data:

For example the parser expects a line of 3 floats: a, b and c. Each column has a width of 10. a is required, b and c are optional. Valid input will look like this:

```
"<---a----><----b---><----c--->"
"1.0       2.0       3.0"
"  1.0     2.0           "
"   1.0 "
"100000000020000000003000000000"
```

How can this be solved?

Thanks in advance!

**Comment by dragostis** [comment]
It's hard to say what you're after. Most like, this is possible to implement, but your definition is ambiguous. I kindly recommend asking this on [Gitter](https://gitter.im/pest-parser/pest).
