### ISSUE TITLE
Warn about unreachable choices

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#241]
```
a* | b
```
`b` is unreachable.

This requires changing the APIs in `pest_meta` to enable warnings apart from errors.

**Comment by wirelyre** [comment]
More generally,

```
nonfailing | unreachable == nonfailing
anything | nonprogressing == anything?
```

**Comment by wirelyre** [comment]
Oops, the second one is wrong. It has to accept the empty string unconditionally. For instance, `"b" | &"a"` is not the same as `"b"?`.
