### ISSUE TITLE
Help with grammar needed

### ISSUE THREAD

**Issue by snsmac** [pest-parser/pest#250]
Hello, i have the following grammar:
```
ident = @{
    !(keyword)
     ~ (alpha | "_")  ~ (alpha_numeric | "_" )*
}

keyword = {
    ^"a" |
    ^"abort" |
    ^"abs" |
   many more words
}
```

Is there a good way to write it so that "ab" is a valid ident? Or is this not possible in a  nice way with a PEG?

**Comment by dragostis** [comment]
Sure. You can set it up like this:

```
!(keyword ~ &(non_ident | eoi))
```

**Comment by snsmac** [comment]
Thanks for the help and this project in general
