### ISSUE TITLE
Mark internal rules visually

### ISSUE THREAD

**Issue by torkleyy** [pest-parser/pest#251]
Hey! I just looked for a parser and I found the pest syntax pretty good to understand. However, I think it would be even more self-explanatory if rules with special meaning started with a `_`. That would require changing the 4(?) "internal" rules to `_whitespace`, `_comment`, `_soi`, `_eoi`.

If you are in favor of this change, I suggest we make both valid first and warn if there is an occurrence without an underscore.

**Comment by dragostis** [comment]
We're working on a syntax like that. The special rules are going to be specified in all-caps; you can find more in one of the issues. Sorry for the brevity, I'm replying from my phone.

We have to come up with a solution for people who will have their 1.0 grammars broken. (Maybe an auto-fix?)

Anyway, thanks a lot for the feedback! I'm more than happy to direct you to anything that you might want to tackle.

**Comment by torkleyy** [comment]
Thanks, that works, too :)
