### ISSUE TITLE
Put the include_str into generated code rather than require users to write down it

### ISSUE THREAD

**Issue by upsuper** [pest-parser/pest#260]
It should be trivial to put an `include_str` into the parser impl, probably as a const inside the parse function, to inform the compiler that it has a dependency to the specific grammar file.

With that, users wouldn't need to write an `include_str` outside like demonstrated in the document, and they don't need to know the complexity about how compiler tracks such dependency.

**Comment by dragostis** [comment]
Unfortunately, this does not currently work, because the generator only knows the Cargo path and the `include_str` only knows the current file path and there seems to be no way to get one information in the other place. Might be a good idea to lobby for file tainting functionality in `proc_macro2`.

**Comment by upsuper** [comment]
Maybe pass the absolute path to `include_str`?

**Comment by dragostis** [comment]
Does that work? The documentation only specifies relative paths.

**Comment by dragostis** [comment]
Will look into it. Would be really nice of this worked out. Thanks for the tip. :smile:

**Comment by LEXUGE** [comment]
But `include_str!` requires string literal. And `Path` can only convert to `String` and `&str`.
I think there's no way to convert `Path` to string literal(`&'static str`).
So how to solve these problem?

**Comment by CAD97** [comment]
In the derive, we would take the `Path` and turn it into a `String`, then use that to create a [`LitStr`](https://docs.rs/syn/0.14.9/syn/struct.LitStr.html) which is then put in the generated output.

**Comment by LEXUGE** [comment]
@CAD97 what is "generated output"?
