### ISSUE TITLE
Missing tag/release for pest_derive 1.0.8

### ISSUE THREAD

**Issue by nirvdrum** [pest-parser/pest#262]
pest_derive 1.0.8 is available on crates.io with a release date of 16-Aug-2018. I was hoping to see what changed in this version, but it's not tagged or "released" on GitHub. It'd be helpful if you someone could tag the release whenever they get a chance.

**Comment by wirelyre** [comment]
As far as I can tell, the crates.io release is at a7e97906bbc0e6582a6cd7009225fa9ef7a985f6.

See https://github.com/pest-parser/pest/compare/v1.0.7...a7e97906bbc0e6582a6cd7009225fa9ef7a985f6 for the diff in GitHub's browser.

**Comment by dragostis** [comment]
pest 1.0 is no longer maintained.
