### ISSUE TITLE
Reserve _ rule?

### ISSUE THREAD

**Issue by CAD97** [pest-parser/pest#263]
[This should be a 2.0 blocker for a decision, then implementation if decided in favor]

As I mentioned previously in the Gitter chatroom, `_` is currently a valid rule name.

If we want to allow making parts of a rule silent, atomic, or otherwise apply modifiers to portions of rules and not whole rules, it would probably be beneficial to reserve the `_` rule name for that syntax.

Until said functionality is implemented, this could be done as a verifier level deny "lint", or it could be done at the grammar level by disallowing a single `_` as an identifier.

```diff
-identifier = @{ !"PUSH" ~ ("_" | alpha) ~ ("_" | alpha_num)* }
+identifier = !{ !"PUSH" ~ ("_" ~ ("_" | alpha_num)+) | (alpha ~ ("_" | alpha_num)*) }
```

**Comment by dragostis** [comment]
Future-proofing this sounds good. This can easily be added as a `pest_keyword`.
