### ISSUE TITLE
Example doesn't work without tiny fix

### ISSUE THREAD

**Issue by axic** [pest-parser/pest#266]
The example in https://github.com/pest-parser/pest#elegant-grammar if not terminated with a new line will result in a macro error:
```
error: proc-macro derive panicked
 --> src/lib.rs:7:10
  |
7 | #[derive(Parser)]
  |          ^^^^^^
  |
  = help: message: error parsing "ident.pest"
          
           --> 8:11
            |
          8 |           // ident_list rule is silent which means it produces no tokens
            |           ^---
            |
            = expected rule

error: aborting due to previous error

error: Could not compile `ident`.
```

Adding a new line character  to the comment line makes this go away.

I am not sure if it is desired, but perhaps a different example where this common mistake doesn't appear might be a good idea.

**Comment by dragostis** [comment]
Thanks for the issue. This is fixed on master and 2.0 should land soon enough, so I'm going to close this.
