### ISSUE TITLE
No link to the pest book on the crates.io or github page

### ISSUE THREAD

**Issue by measlytwerp** [pest-parser/pest#282]
I was trying to find information about the syntax in the docs and the github repo, but wasn't having any luck until I stumbled on a mention of a 'book' in an issue.

Perhaps the book should be set as the project home page in the crate, and linked to on the github repo?

Otherwise I'm not sure how you'd find it without knowing about it.

**Comment by measlytwerp** [comment]
Until I found the book I wasn't aware that you had a github page, you should set that as the homepage in Cargo.toml so that it's linked to at the top of your crates.io page:

```toml
homepage = "https://pest-parser.github.io/"
```

As for the book, it would be good if it was mentioned in the "Elegant grammar" section of the readme, as that's where I was looking for information about it. I hadn't even considered that there'd be a link to documentation amongst the badges.

**Comment by dragostis** [comment]
Fixed.
