### ISSUE TITLE
pest_meta is still on 1.0

### ISSUE THREAD

**Issue by SergejJurecko** [pest-parser/pest#288]
Switching to pest 2.0 now means both versions are compiled and used because pest_meta is still on 1.0. A bit annoying.

**Comment by dragostis** [comment]
Unfortunately, Cargo doesn't yet support prebuilt binaries, so we're currently keeping 1.0 around in order not have a long compilation chain. I'm also open to ideas on how to bootstrap pest more gracefully than this.

As a side note, I don't think that compiling a few extra not so large crates once is a huge paper-cut, but it would be nice to at least have a way to keep the meta grammar up to date.

**Comment by CAD97** [comment]
Bootstrap chain is broken via vendoring the compiled grammar on crates-io, then using the version from crates-io for local development. This means that to compile pest from GitHub sources requires a pre-processed grammar file, most likely from crates-io, but it also means that crates-io users will no longer need to build pest:1.0 to build pest:2.0. 🎉
