### ISSUE TITLE
Getting position/span from Error

### ISSUE THREAD

**Issue by sunng87** [pest-parser/pest#307]
handlebars is using the line/col number from pest `Error` for error reporting. From 2.0, it seems no way to get from the `Error` struct. I suggest to hold the `Position` or `Span` within `InputLocation` and provide getters for them.

**Comment by dragostis** [comment]
You can use `Error`'s [location](https://docs.rs/pest/2.0.1/pest/error/struct.Error.html) for that purpose.

**Comment by dragostis** [comment]
That would be unsafe. Why do you need the `Position`?

The reason this was changed was because it was hard to own an `Error` with a lifetime.

**Comment by sunng87** [comment]
I need line/col number from Position for error reporting.

**Comment by dragostis** [comment]
We should add two methods to `InputLocation` that take an `input` and return `Option`s with their specific outputs, i.e. `line_of` and `line_col`. (if UTF-8 bound check out)

**Comment by sunng87** [comment]
How about to make light-weighted `Position` and `Span` that only  holds pos, line/col no and some relative position information without holding reference for `Input`. For any operation that needs return data from `Input`, pass it as parameter.

**Comment by dragostis** [comment]
How would that differ from `InputLocation`? `InputLocation` could live in a separate module and be the exclusive way to get `line_col` and `line_of` information.

**Comment by sunng87** [comment]
hmmm, I wish line_col can be cached in `Position` so we don't have to recompute it from `Input`. For other cases, I think it's identical to current `InputLocation`.

**Comment by dragostis** [comment]
`Error` already save some of this [data](https://github.com/pest-parser/pest/blob/master/pest/src/error.rs#L93).

**Comment by sunng87** [comment]
Then the only thing I need is to expose `start`: https://github.com/pest-parser/pest/blob/master/pest/src/error.rs#L31

**Comment by dragostis** [comment]
I wonder how the cached line/col information should be exposed.

**Comment by sunng87** [comment]
Maybe simply publicize the `start` and `end` fields?
