### ISSUE TITLE
Changes in grammar file not picked up by cargo for rebuild

### ISSUE THREAD

**Issue by birkenfeld** [pest-parser/pest#320]
This is probably not possible to solve within pest... it would require a build.rs-like API to add dependency files.

But maybe a hint in the documentation may make sense?

**Comment by callum-oakley** [comment]
If you stick a

```rust
const _GRAMMAR: &str = include_str!("your_grammar_file.pest");
```

in your source, then changes will be picked up.

**Comment by birkenfeld** [comment]
Right. Then maybe this issue should be "stick `include_str!` into the derived code by default" :smile:

**Comment by CAD97** [comment]
This should be the case in pest:2.0.2 already

**Comment by birkenfeld** [comment]
Ah - it works indeed, but only in a debug build. Not in release...

**Comment by birkenfeld** [comment]
Which is unsurprising, looking at https://github.com/pest-parser/pest/blob/master/generator/src/generator.rs#L162

Why is that restricted to `#[cfg(debug_assertions)]`? The constant will be optimized away anyway, no?

**Comment by dragostis** [comment]
I'm considerig whether we should keep this for debug only or not. It will probably be optimized out anyway, but this is not guaranteed.

I also see how this could be an issue when developing on release builds, e.g. when profiling for performance. Any thoughts?

**Comment by lwandrebeck** [comment]
As release builds _may_ reveal some strange behaviour compared to debug ones, I’d vote for having it in both modes. Though one should check that « will probably be optimized out » is indeed « is optimized out » ;)

**Comment by birkenfeld** [comment]
I did check this, for one project and nightly rustc.

Later the potential wasted space could be reduced by doing `&include_str!()[..0]` or `include_str!().len()` but both seem not to be stable yet.
