### ISSUE TITLE
Parsing ML-style Function Application

### ISSUE THREAD

**Issue by fmrl** [pest-parser/pest#323]
Is it possible, with `pest`, to parse ML-style function application? i.e.:
```
WHITESPACE = ...
expression = {
   application |
   subexpression |
   ...
}
application = { expression ~ expression }
```
I understand that the left-recursive problem is involved.

Thanks in advance.

**Comment by dragostis** [comment]
Generally, one should use the repetition oprrators and lookaheads (`&` and `!`) in order to avoid left-recursion. Function application should easily be parsable. As a general rule of thumb, no CFG grammar was found that is unexpressible in PEG grammars which pest is built on.

**Comment by fmrl** [comment]
> As a general rule of thumb, no CFG grammar was found that is unexpressible in PEG grammars which pest is built on.

this is good to hear; `pest` is my favorite parser for rust so far.

i tried using the `&` operator, i.e.:

```
WHITESPACE = ...
expression = {
   application |
   subexpression |
   ...
}
application = { &(expression ~ expression) ~ expression ~ expression }
```

i got a similar error message. is there something i'm missing?

**Comment by fmrl** [comment]
i think i've figured it out. thanks for the assistance. 😄
