### ISSUE TITLE
Incompatibility with missing_docs lint

### ISSUE THREAD

**Issue by librelois** [pest-parser/pest#326]
I must have disabled `missing_docs` lint to compile my crate, it's very annoying, the compiler no longer checks that all the documentation is present : 

```
error: missing documentation for an enum
  --> documents/v10/mod.rs:38:10
   |
38 | #[derive(Parser)]
   |          ^^^^^^
   |
note: lint level defined here
  --> documents/lib.rs:20:5
   |
20 |     missing_docs,
   |     ^^^^^^^^^^^^

error: missing documentation for a variant
  --> documents/v10/mod.rs:38:10
   |
38 | #[derive(Parser)]
   |          ^^^^^^

error: aborting due to 2 previous errors
```

**Comment by dragostis** [comment]
Hm, this is interesting. The `Rule` enum is mostly thought out to be used in the implementation of your crate and not in user-facing APIs. How are you using the derive?

**Comment by librelois** [comment]
My Struct `ParserV10` is private.  
I migrate to pest a lib crate that is used to parse documents of a specific protocol.
This crate is called `duniter_documents` and is not intended for use in user-facingAPI.

Thank you for your reactivity, my code is here: https://git.duniter.org/nodes/rust/duniter-rs/blob/migrate_to_pest/documents/v10/mod.rs#L40
(Migration from regex to pest is a work in progress)

**Comment by CAD97** [comment]
As a short-term solution, you can add `#[allow(missing_docs)]` to the module in which you're defining the parser.

**Comment by attila-lin** [comment]
Hi. Any progress? I think the pr may work.

**Comment by tomtau** [comment]
I pinged the author. If they don't respond, I can reopen a PR with a fix to add the missing comment to EOL

**Comment by woodruffw** [comment]
I'm seeing a variant of this still with `pest 2.8.0`:

```
error: missing documentation for a variant
  --> crates/github-actions-expressions/src/lib.rs:12:10
   |
12 | #[derive(Parser)]
   |          ^^^^^^
   |
note: the lint level is defined here
  --> crates/github-actions-expressions/src/lib.rs:4:9
   |
4  | #![deny(missing_docs)]
   |         ^^^^^^^^^^^^
   = note: this error originates in the derive macro `
```

The code in question:

```rust
#[derive(Parser)]
#[grammar = "expr.pest"]
struct ExprParser;
```

Adding `pub(crate)` also doesn't suppress it, unfortunately.

**Comment by woodruffw** [comment]
@tomtau Thanks for the fast response! My understanding was that I didn't need docs on those variants since the parser itself isn't `pub`. But it's possible I'm misunderstanding how `missing_docs` and `pub` interact -- if visibility isn't a factor then please ignore me 🙂

**Comment by woodruffw** [comment]
Thanks a ton, that did the trick! I had to explicitly give it a `pub` qualifier within the private crate, but otherwise that worked perfectly:

```rust
mod parser {
    use pest_derive::Parser;

    /// A parser for GitHub Actions' expression language.
    #[derive(Parser)]
    #[grammar = "expr.pest"]
    pub struct ExprParser;
}
```
