### ISSUE TITLE
Handling indentation

### ISSUE THREAD

**Issue by flying-sheep** [pest-parser/pest#329]
Hi! I don’t know if this is a question or a feature request, but I want to parse [reStructuredText](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html). It allows nesting blocks, and [indentation works in a special way](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#indentation):

> Several constructs begin with a marker, and the body of the construct must be indented relative to the marker. For constructs using simple markers (bullet lists, enumerated lists, footnotes, citations, hyperlink targets, directives, and comments), the level of indentation of the body is determined by the position of the first line of text, which begins on the same line as the marker. For example, bullet list bodies must be indented by at least two columns relative to the left edge of the bullet:
> 
> ```rst
> - This is the first line of a bullet list
>   item's paragraph.  All lines must align
>   relative to the first line.  [1]_
> 
>       This indented paragraph is interpreted
>       as a block quote.
> 
> Because it is not sufficiently indented,
> this paragraph does not belong to the list
> item.
> 
> .. [1] Here's a footnote.  The second line is aligned
>    with the beginning of the footnote label.  The ".."
>    marker is what determines the indentation.
> ```
> 
> For constructs using complex markers (field lists and option lists), where the marker may contain arbitrary text, the indentation of the first line after the marker determines the left edge of the body. For example, field lists may have very long markers (containing the field names):
> 
> ```rst
> :Hello: This field has a short field name, so aligning the field
>         body with the first line is feasible.
> 
> :Number-of-African-swallows-required-to-carry-a-coconut: It would
>     be very difficult to align the field body with the left edge
>     of the first line.  It may even be preferable not to begin the
>     body on the same line as the marker.
> ```

How can I parse this? Would I parse it manually, I’d define an “indent stack” (like `[2, 4]` for the first example). Is the best idea to create an iterator that handles this indent stack and only feeds the blocks it found into `pest`? Or is there another way?

**Comment by dragostis** [comment]
#328 should be helpful here. Let me know if you need extra help and I can take a closer look!

**Comment by flying-sheep** [comment]
Not exactly, as indentation isn’t defined by just the spaces that can be pushed on the stack (as mentioned in the text). The markers also count.

Furthermore, I’d need a way to say “if the stack is empty, match "".” AFAIK, `PEEK` fails to match on an empty stack. I *assume* I’d need the following extensions

- `PEEK` → `PEEK` (as before) or `PEEK(default)` (matches “default” if the stack is empty)
- `PUSH` → `PUSH(expr)` (as before) or `PUSH(expr, lambda)` (executes the lambda on the captured range and pushes the return value)

and then I could do:

```peg
block = { PEEK("") ~ (bullet_list | …) }
bullet_list = { (bullet_list_item | empty_line)+ }
bullet_list_item = { PUSH("-" ~ " "+, m => m.replace('-', " ")) ~ line ~ block* }
line = { !bullet_list_item ~ ANY* }
```

**Comment by dragostis** [comment]
Markers can probably be dealt with by having multiple choices:

```
block = { "-" ~ bullet_list | "^" ~ whatever }
bullet_list = { ... }
whatever = { ... }
```

Why do you need to know when the stack is empty?

**Comment by dragostis** [comment]
I see the issue with the pushes, though. You'd need a way to simply figure out the distance from the start of the line. I'm wondering what the smallest primitive is in order to enable this.

**Comment by flying-sheep** [comment]
> You'd need a way to simply figure out the distance from the start of the line.

This is problem 1:

If I want to populate the stack with the indentation, I need to be able to push `" "{x}` onto the stack, while matching `something{y} ~ " "{x-y}` (e.g. I match `"-" ~ " "{2}` and push `" "{3}`)

Of course if there would be another way than the stack, that would work too, but having a stack is the most intuitive.

> Why do you need to know when the stack is empty?

This is problem 2:

Provided the stack contains the indentations of the first example, i.e. `["  ", "    "]`, I’d match the indentation via `PEEK ~ line`. But that should also work on an empty stack!

I could just do `document = { SOI ~ PUSH("") ~ block* ~ EOI }`, but then I can’t test rules right? `RstParser::parse(Rule::block, ...)` wouldn’t match, since `parse` initializes the stack empty and `PEEK` will not match an empty stack.

**Comment by dragostis** [comment]
I've managed to get [something](https://pest-parser.github.io/?bin=14tp26#editor) working. The issue here is that the order of pushing vs the order of popping is reversed, but it works if spaces only contains spaces and not tabs, for example.

**Comment by flying-sheep** [comment]
Hmm, that doesn’t work. All kinds of blocks can be nested (your `rest_lines?` should be something like `block*`)

I tried something, but I can’t get it to work: https://pest-parser.github.io/?bin=nsp5q#editor

i’m not sure if it’s possible using PUSH/POP semantics

**Comment by dragostis** [comment]
I think this is possible by using `PEEK_ALL`, like in the simple lists [example](https://github.com/pest-parser/pest/blob/master/derive/tests/lists.pest). It uses `PUSH` and `DROP` in order to keep track of the indentation level.

**Comment by flying-sheep** [comment]
I got it. Damn, that’s hard, but you’re right, it is possible.

https://pest.rs/?bin=ytvrq#editor

**Comment by dragostis** [comment]
Super impressive work! 😃I really like the elegance of your example. Your example is missing a `PEEK_ALL` in [the beginning of `bullet_list`](https://pest-parser.github.io/?bin=jrtvq#editor).

`PEEK_ALL` always matches when the stack is empty. Unfortunately, this needs to be better documented.

**Comment by dragostis** [comment]
I don't have a complete solution, but the issue in your example is that you need to `PEEK_ALL` at every line, but `line` accepts the new line, then calls `blist_body` which should first `PEEK_ALL` before doing anything else, but doesn't.

```
bullet_item =  { "-" ~ PUSH(" "+) ~ line ~ blist_body? ~ DROP }
blist_body  = _{
  // Some PEEK_ALL is needed here
  PUSH(" " ~ POP) ~ hanging_block ~ block*
}
```

This is quite hard since, as far as I can tell, you always need to figure out if you're a paragraph or a bullet list item. Maybe you could make use of the lookahead like this:

```
  &(PEEK_ALL) ~ paragraph          // paragraph at same indentation
| &(DROP ~ "-" ~ ...) ~ blist_item // bullet list item at same parent indentation
```

**Comment by flying-sheep** [comment]
I don’t think it’s possible. `blist_body` appears when the stack contains `[…, "- "]`, so i’d need `PEEK_ALL_EXCEPT_LAST ~ PUSH(" " ~ POP)`.

**Comment by dragostis** [comment]
I guess the lookahead won't work because after you'd need to actually match it, correct?

If so, it might be worthwhile to be able to peek by slicing the stack with a range, I presume. Adding this would be no problem.

**Comment by flying-sheep** [comment]
Should I create a separate issue for this?

and how would it look? I would propose arrow slice syntax:

`PEEK`, `PEEK[i]`, `PEEK_ALL[start..end]`, `PEEK_ALL` (`start` and `end` are optional, default to start and end of the stack, so `PEEK_ALL[..]` is equivalent to `PEEK_ALL`)

I propose that the brace syntax fails when you specifically request an item that doesn’t exist, but succeeds when you request an empty sequence.

E.g. if there’s one item on the stack (`PEEK_ALL ≡ ("stuff")`)

1. `PEEK[-2]` fails
2. `PEEK_ALL[-2..]` fails
3. `PEEK[-1] ≡ "item"` succeeds
4. `PEEK_ALL[..-1] ≡ ()` succeeds

**Comment by dragostis** [comment]
I've been thinking about pretty much exactly the same syntax, only having both negatives and positives. I was considering whether this should be added as a more conservative feature now in a 2.1 release or whether this should be part of a big, 3.0 pest syntax RFC that would include this change.

**Comment by dragostis** [comment]
I feel more inclined to have this working in 2.1 without guaranteeing syntax stability post-3.0. @flying-sheep, would you like to take a jab at this? If not, I can give it a try. :)

**Comment by dragostis** [comment]
Yes, but you'd be able to use both negative and positive ends.

**Comment by flying-sheep** [comment]
of course. it would work just like python slicing, only with `..` instead of `:`

**Comment by dragostis** [comment]
Precisely! If there's one thing they got right in Python, it's slicing.

**Comment by dragostis** [comment]
Oh, and, I'm here to offer guidance for this. Generally, it shouldn't be very hard to incorporate this since it's split in very granular tasks, but there might be a few caveats here and there, e.g. with validation.

**Comment by dragostis** [comment]
@flying-sheep, pretty sure constrained types are still a long ways off, but here's hoping!

Modifying the grammar is a good place to start. After that, some changes need to be made to generator in order to slice the `Stack` found in pest itself.
