### ISSUE TITLE
Interested in a vim hilighting plugin?

### ISSUE THREAD

**Issue by phaazon** [pest-parser/pest#340]
I can write a (neo)vim plugin to hilight the PEG-pest grammar syntax, if you are interested and that it doesn’t already exist. It should be done pretty quickly. :)

**Comment by dragostis** [comment]
There is [this](https://github.com/pest-parser/pest.vim), but I'm afraid it's not up to date anymore. Feel free to change is as needed! 😃

**Comment by phaazon** [comment]
I will for sure!

**Comment by tomtau** [comment]
it seems https://github.com/pest-parser/pest.vim received some updates, but feel free to open any issues or PRs there.
Maybe also good to have a dedicated maintainer of that Vim plugin? https://github.com/pest-parser/pest/discussions/606
