### ISSUE TITLE
Need help in handling Left Recursion for SQL parser

### ISSUE THREAD

**Issue by vnnv01** [pest-parser/pest#342]
Hi All,

I am tyring to do SQL parsing using Pest Grammar Files.

I converted the below Teradata Antlr grammar file to rust and I get the left recursive error

https://github.com/cmedved/Teradata-SQL-Parser/blob/master/src/main/java/us/shadowlabs/tdparser/antlr/Teradata.G4

section [204 to 229 ] of ANTLR code. from the above file having issue.

```
expr
: literal_value
| column_name
| unary_operator expr
| expr ‘||’ expr
| expr ( '’ | ‘/’ | ‘%’ ) expr
| expr ( ‘+’ | ‘-’ ) expr
| expr ( ‘<’ | ‘<=’ | ‘>’ | ‘>=’ ) expr
| expr ( ‘=’ | ‘==’ | ‘!=’ | ‘<>’ | K_IS | K_IS K_NOT | K_IN | K_LIKE ) expr
| expr K_AND expr
| expr K_OR expr
| function_name ‘(’ ( K_DISTINCT? expr ( ‘,’ expr ) | '’ )? ‘)’
| ‘(’ expr ‘)’
| K_CAST ‘(’ expr K_AS type_name ‘)’
| expr K_NOT? K_LIKE expr ( K_ESCAPE expr )?
| expr ( K_IS K_NULL | K_IS K_NOT K_NULL | K_NOT K_NULL )
| expr K_IS K_NOT? expr
| expr K_NOT? K_BETWEEN expr K_AND expr
| expr K_NOT? K_IN ( OPEN_PAR ( select_expr
| expr ( ‘,’ expr )
)?
CLOSE_PAR
| ( database_name ‘.’ )? table_name )
/*| ( ( K_NOT )? K_EXISTS )? ‘(’ select_stmt ‘)’ */
| K_CASE expr? ( K_WHEN expr K_THEN expr )+ ( K_ELSE expr )? K_END
;
```
I think above scenario is similar to below code.

```
expr1 = {ASCII_DIGIT
|expr1~("+"|"-")~expr1
}

```
If I try to parse the statement `2+2+3` then grammar parser only `2 `and not the rest. So how can we resolve this.

I am newbie to grammar parsing. Thanks for your help in advance.

Thanks,
Vignesh

**Comment by dragostis** [comment]
Thanks for your interest in pest!

If you have limited experience with grammars, I highly suggest trying out the [pest book](https://pest.rs/book/). It's fairly short and covers a decent amount of concepts.

**Comment by vnnv01** [comment]
Thanks for your response. Yeah I read the book and I was able to convert most of the grammar file based on the book. I was able to parse the other parts of grammars as well using pest. However I am stuck with the left recursion can you give me a direction how to solve it.  For the example mentioned above.

**Comment by dragostis** [comment]
For unary + infix operators you could do something like this:

```pest
expr = { term ~ (infix_op ~ term)* }
term = {
    "(" ~ expr ~ ")" |
    unary_op ~ expr |
    ...
}

infix_op = { ... }
unary_op = { ... }
```

You can then use pest's precedence climber when processing the token pairs.

**Comment by vnnv01** [comment]
Hi Dragostis,

I am able to convert the grammar file as you mentioned into below format. It worked.

``inflix_op = { "||"|"*"|"/"|"%"|"+"|"-"|"<"|"<="|">"|">="|"="|"=="|"!="|"<>"|K_IS|K_IS~K_IS~K_NOT|K_IN|K_LIKE 
|( K_NOT?~K_LIKE)
|( K_IS~K_NULL | K_IS~K_NOT~K_NULL | K_NOT~K_NULL )
|(K_IS~K_NOT?)
|(K_NOT?~K_BETWEEN)
|(K_NOT?~K_IN)
|(K_AND)
}``

``cast= { K_CAST~"("~expr~K_AS~type_name~K_FORMAT~date_format~")" | K_CAST~"("~expr~K_AS~type_name~")" }``
``date_format= @{^"'YYYYMMDD'"}``
``case_when = { K_CASE~expr?~(K_WHEN~expr~K_THEN~expr)+~(K_ELSE~expr)?~K_END }``
``function_name_expr = { function_name~"("~(K_DISTINCT?~expr~(","~expr)*|"*")?~")"}``
``expr_inside_paran = { "("~expr~")" }``

``expr = { term ~ ( inflix_op ~ term)* }
term={
cast
|case_when
|function_name_expr
|expr_inside_paran
|(K_ESCAPE~expr?)
|literal_value
|column_name
|(OPEN_PAR~(select_expr| expr~(","~expr)*)?~CLOSE_PAR|(database_name~".")?~table_name)
}``
Closing this issue.
