### ISSUE TITLE
LifeTime issue when Returning Pair<Rule>

### ISSUE THREAD

**Issue by vnnv01** [pest-parser/pest#346]
Hi Team,

I am trying to use the following  function defintion to get a pair<Rule> as output based on the input Rule. This function works without return type. 
``
fn get_rule<'a>( sfp:&'a FlatPairs<Rule>,r:Rule) -> &'a Pair<Rule>

    let  sr : Pair<Rule>   ;
    for i in sfp
        {
            if i.as_rule() == r  {
                sr=i.clone();
                println!("The value of sr is {:?}",sr);
                break;
            }
        }
     return sr;

}
``

However the moment I add return type I get the below error.  I tried without lifetime and with lifetime as well and without returning reference and with reference as well. Error is at the point Pair<Rule>. I am not sure what I am missing. Please help. I am not sure why it says 2 sfp variable . 

```
    |
355 | fn get_rule<'a>( sfp:&'a FlatPairs<Rule>,r:Rule) -> &'a Pair<Rule>{
    |                                                         ^^^^^^^^^^ expected lifetime parameter
    |
    = help: this function's return type contains a borrowed value, but the signature does not say which one of `sfp`'s 2 lifetimes it is borrowed from
```

**Comment by dragostis** [comment]
`Pair` takes the input's lifetime as a parameter as well, so it should be `Pair<'i, Rule>`. You can see the definition in the docs or source code.

**Comment by vnnv01** [comment]
Thanks sir again , Modifying the code as below solved the issue .

```
fn get_rule<'a>( sfp:&'a FlatPairs<Rule>,r:Rule) ->  Option<Pair<'a, Rule>>{
    let   sr : Pair<Rule>    ;
    let sfp_clone = sfp.clone();
    for i in sfp_clone
        {
            if i.as_rule() == r  {
                sr=i.clone();
                return Some(sr);
            }
        }
     return  None;


}
```

**Comment by dragostis** [comment]
No problem at all! 😃
