### ISSUE TITLE
Integer underflow in Error::fmt

### ISSUE THREAD

**Issue by flying-sheep** [pest-parser/pest#348]
Trying to display an error created from a `Span((8, 11), (9, 1))` results in an error.

This is because when trying to reverse the underline, `start` gets set to 0 before the line `let offset = start - 1` is executed.

https://github.com/pest-parser/pest/blob/49847de8f41badc14c353c8f221a92fc5e376ee8/pest/src/error.rs#L266-L280

This occurs if the span points to the first char of the new line, which happens when `\n` is the last matched char. I think the actual span that should be underlined in that case is the one ending one char earlier, on the previous line.

**Comment by dragostis** [comment]
Thanks for reporting this. Underlining the character before makes a lot of sense. This code there is quite sensitive and has a lot of edge cases. I had hoped that it was decently well-tested, but that doesn't seem to be the case.
