### ISSUE TITLE
Need help in converting Antlr Grammer 

### ISSUE THREAD

**Issue by vnnv01** [pest-parser/pest#351]
Hi Team,

I am trying to convert the following grammar of antlr to pest. 

```
IDENTIFIER
 : '"' (~'"' | '""')* '"'
 | '`' (~'`' | '``')* '`'
 | '[' ~']'* ']'
 | [a-zA-Z_] [a-zA-Z_0-9]*
;
```
to

`IDENTIFIER = @{ ("\""?~ASCII_ALPHA~(("\""~"\"")|ASCII_ALPHANUMERIC|"_")*~"\""?)`

Antlr grammar is able to reject the string `solar"system`.. whereas pest returns `solar"`. I know I am making mistake in pest grammar it matches the quotes and mark the end of identifier. 

What should be my grammar if I want pest to behave like antlr. 

Please give me any clue.

Thanks in advance.

**Comment by vnnv01** [comment]
Hi Sir,

Thanks for your reply.

I think rule in link is not working.  It still returns `solar`. 
 
This rule is used in SQL. In sql, we can have object_name with double quotes Eg.

```
create table "test_1""_2" ( id int);
dbadmin=> select * from "test_1""_2" ;
 id
----
(0 rows)
```

**Comment by dragostis** [comment]
This is just a difference in parsing techniques: a top-down parser like pest will accept `solar` in your example but will err when its parent rule finds the `"` after it instead of a keyword, for example.

**Comment by vnnv01** [comment]
oh got it. Thanks sir again for your prompt response. I am planning to change rule from `any` to `id`
```

IDENTIFIER = {
	  "\"" ~ (!"\"" ~ id | "\"\"")* ~ "\""
    | "'" ~ (!"'" ~ id | "''")* ~ "'"
    | "[" ~ (!"]" ~ id)* ~ "]"
    | id 
    
}
id ={(ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")*}
```
