### ISSUE TITLE
Unable to iterate Pair::into_inner(self, ...) without consuming Pair

### ISSUE THREAD

**Issue by frehberg** [pest-parser/pest#358]
the function "Pair::into_inner(self,..)" is consuming the pair. I would like to see a function in API just borrowing the pair, something like "Pair::inner(&self, ..)"

**Comment by frehberg** [comment]
@CAD97  Thanks for the explanation :) 
I found documentation explaining the Grammar, but I did not find any documentation, explaining the usage of the API of pest, for example explaining
* Traversing the tree using "for subnode in node.clone().into_inner() {..."
* Reading the type of a node using "subnode.as_rule()" returning a variant of enum Rule
* And how the grammar is related to the enum Rule
* How to access the underlying token/identifier, such as using "node.as_str()"
Using the API I wished for some macro I could use to perform pattern matching. Maybe, are you planning for such macros?

**Comment by arabidopsis** [comment]
So if I want to generate two different structs from the same parser then
is pair.clone().into_inner() the way to go? .... to avoid the consumption? Or is
it just faster to re parse the same string then consume the pairs?

**Comment by CAD97** [comment]
You'll definitely want to clone the pair. Parsing is expensive and cloning the parsed tree is just an Arc clone.
