### ISSUE TITLE
Error messages include ␊ on all lines

### ISSUE THREAD

**Issue by markbt** [pest-parser/pest#362]
https://github.com/pest-parser/pest/commit/95881fd2e3a4fc278f73326b5a86b079eda41d24 changed `Error` so that both `new_from_pos` and `new_from_span` variants have `visualize_whitespace` called.  Prior to this, only `new_from_pos` variants had their whitespace visualized.

This has the side-effect of making *all* error messages include replacement symbols for their terminating newline.  You can see this on the pest editor here: https://pest-parser.github.io/?bin=18hayc#editor

```
 --> 1:1
  |
1 | goodbye␊
  | ^---
  |
  = expected hello
```

The extra LF symbol (␊) is confusing for end users, and is noise in cases like this where whitespace is irrelevant.  I would expect CR and NL to only be visualized when they are important to the error.

**Comment by dragostis** [comment]
Thanks for reporting this. I completely agree. If anyone won't grab this in the next few days, I'll fix this myself. If you need this urgently, I'll release a fixed version right away.

**Comment by markbt** [comment]
Not urgent.  For now we will live with the extra LFs in the error messages.  Thanks for looking into it!

**Comment by loewenheim** [comment]
If I understand this correctly, the fix involves just removing the calls to `visualize_whitespace` from `new_from_span`? If so, I can open a pull request.

**Comment by dragostis** [comment]
I believe one would need to remove it from `new_from_pos`?

**Comment by PvdBerg1998** [comment]
Hello, I'm new to using Pest and indeed found this to be confusing and assumed it was a bug. Did you have a fix @dragostis ?

**Comment by dragostis** [comment]
@PvdBerg1998, I haven't had so much time to fix stuff lately. Feel free to open a PR for this.
