### ISSUE TITLE
pest's generated ast does not include built-in rules

### ISSUE THREAD

**Issue by ixjf** [pest-parser/pest#366]
I was just working with pest and I realized that the generated AST was not including built-in rules like 'ASCII_ALPHA_UPPER'. I'm not sure if this is intended behaviour, but I don't see any reason why that would be so.

A quick example of that:
```
rule1 = { ASCII_ALPHA_UPPER ~ rule2 }
rule2 = { "0" }
```

With an input of "A0", this produces a pair for 'rule1', whose span is "A0", but which has an only child 'rule2'. I would expect there to be a rule for 'ASCII_ALPHA_UPPER' as well.

**Comment by dragostis** [comment]
Built-in rules are silent by default and it's fairly easy to change that by wrapping them:

```pest
my_alpha_upper = { ASCII_ALPHA_UPPER }
```

The reason for this is that creating a token for every character would be computationally expensive and should happen only in cases where it's *really* needed.
