### ISSUE TITLE
Feature request: Pestfile formatter

### ISSUE THREAD

**Issue by alok** [pest-parser/pest#367]
Not a priority, but it'd be nice to be able to have the equivalent of rustfmt for pestfiles.

**Comment by dragostis** [comment]
Can rustfmt be extended for this purpose?

**Comment by GalAster** [comment]
I have made a basic implementation

https://github.com/pest-parser/pest-fmt/blob/master/tests/test.rs

The currently supported styles can be found in the `out` folder

---

Next I am ready to support more styles and options

I also need some help to develop a cli that reads settings from `rustfmt.toml` and formats the entire project

**Comment by tomtau** [comment]
This seems to be done, potentially follow ups can be worked on in https://github.com/pest-parser/pest-fmt
Also perhaps good to have a dedicated maintainer: https://github.com/pest-parser/pest/discussions/606 for the formatter ?
