### ISSUE TITLE
Strict rules

### ISSUE THREAD

**Issue by mrLSD** [pest-parser/pest#373]
I have problem with strict rules parsing.

My Pest data:
```
letter = { LETTER }
newline 	= { NEWLINE }
unicode_digit  	= { NUMBER }
WHITESPACE 	= _{ " " | "\t" | newline }
identifier 	= @{ !predeclared_identifiers ~ letter+ ~ ( letter | unicode_digit )* }
predeclared_identifiers = { "int" }
```

And rust test code:
```
    let rules = [
        ("int", false),
        ("ints", true), // FAILED
        ("test", true),
        ("test123", true),
        ("the test", false), // FAILED
    ];
    rules.iter().for_each(|(code, expect)| {
        let res = LanguageParser::parse(Rule::identifier, *code);
        if res.is_ok() {
            let res = res.clone().unwrap().next().unwrap();
            dbg!((&res.as_str(), &code));
        }
        assert_eq!(res.is_ok(), *expect);
    });
```

"ints" word are not recognized.
White space are not skipped.

How to implement that rules strictly?

**Comment by adamAndMath** [comment]
The problem with your current version of identifiers is that your predicate is too strong. You are essentially saying that identifiers are not words that start with a predefined identifier. As opposed to words that are not themselves predefined identifiers.
Depending on how the rest of your language is defined I would either do
```
predeclared_identifiers = { "int" ~ !( letter | unicode_digit ) }
```
or
```
identifier 	= @{ !( predeclared_identifiers  ~ !( letter | unicode_digit ) ) ~ letter+ ~ ( letter | unicode_digit )* }
```
With that it should match "ints".

**Comment by adamAndMath** [comment]
Your problem with white space is do to the fact that parsers can match part of a string. In this case your parser accepts "the" as an identifier. If you want to force it to parse the entirety of the string you need to add SOI (Start of input) and EOI (End of input) around your rule.
This is not what you want to do for testing inner rules though. It should be sufficient to simply check if the entirety of the string was accepted.

**Comment by mrLSD** [comment]
Thanks!
