### ISSUE TITLE
Feature request: export lexical information as json/xml/whatever

### ISSUE THREAD

**Issue by ice1000** [pest-parser/pest#377]
I hope there can be a feature that allows us to pretty-print a json/xml/csv/whatever which includes the lexicial information (like token type, pos/line/column), like the AST printer in https://pest.rs but I want an easy way to invoke that locally and get a more easy-to-parse format (I hope it's csv (you can represent nested tree-structure via adding a `depth` attribute in each column), so I don't even need a json parser).

After this, we can make a lot of goodies like some other tools that renders a webpage of code that is syntax-highlighted according to the lexical information.

**Comment by dragostis** [comment]
This would be a pretty easy addition for 2.2. It should come after a feature since we don't want to bring serde as a mandatory dependency.

**Comment by CAD97** [comment]
Implementation sketch: `impl Serialize for Pair && Pairs`. `Pairs` serializes as `{pos: (start, end), pairs: [Pair]}` and `Pair` serializes as `{pos: (start, end), token: Token, inner: (&str | Pairs)`. It doesn't have to be super performant, so doing most of the work through adapter types with `#[derive(Serialize)]`. (That said, `Serialize` isn't too hard to implement correctly manually, so a solution that doesn't use adapter types wouldn't be hard, and `Deserialize` is probably not worth the effort (as we'd have to stuff the full string somewhere or rebuild it)).

**Comment by Goncalerta** [comment]
I'd like to work on this issue

**Comment by dragostis** [comment]
@Goncalerta, that's nice to hear! Feel free to take a jab at it following @CAD97's sketch.
