### ISSUE TITLE
Parsing is slow; any quick wins ?

### ISSUE THREAD

**Issue by Nadrieril** [pest-parser/pest#378]
I'm working with a [rather large grammar](https://gist.github.com/Nadrieril/c4e7548ee83b1dd6a132358491bb8ea8) generated from an ABNF spec. Running it on a medium-sized file (200 lines) is quite slow (8s) and that's a big problem for me.
I realize there are quirks to how PEGs are parsed that may affect performance; are there any best practices or tips I could use to improve performance ?

**Comment by Nadrieril** [comment]
I'd be interested in ways to measure where the performance drop comes from too, if that's possible.

**Comment by Nadrieril** [comment]
Hrm, compiling with --release makes it too fast to matter. Sorry, my mistake.
I'm still interested to know if there are any known antipatterns I should watch out for, but otherwise I can close this issue.

**Comment by dragostis** [comment]
The premise that pest should be able to optimize grammars statically to a degree where small changes shouldn't matter. That is not entirely true right now, but I've been working hard to make this the case in 3.0.

**Comment by Nadrieril** [comment]
Ok, thanks a lot :)
