### ISSUE TITLE
Need to organize functions parsing different rules in different module files.

### ISSUE THREAD

**Issue by vnnv01** [pest-parser/pest#380]
Hi All,

I have multiple rules in grammar file for SQL grammar. 

I would like to create a new module file with all functions for different functionalities like for "Create","Insert","Select".

If I place all the functions for all the rules in main.rs it works. 

If I place it in different module file. It does not work . It says "Rule Does not exist".

I tried importing the following 
``
extern crate pest;
extern crate pest_derive;

use pest::ParserState;
use pest::ParserState::Rule;
use pest::iterators::Pair;
use pest::iterators::FlatPairs;
use pest::Parser;
use pkg::generic_fun;
use std::str;
``

I get the below error. 

``
 | use pest::ParserState::Rule;
  |           ^^^^^^^^^^^ not a module `ParserState`

error[E0432]: unresolved import `pest::ParserState`
  --> src\pkg\generic_fun.rs:10:11
   |
``

Having all the functions for rule in single file is very difficult to organize. Please help.

**Comment by dragostis** [comment]
I don't really follow what the issue here is. pest does not create separate function for grammar rules. It only creates an `enum` called `Rule` that contains all the rules, by name. This is used only as a way to tag them.

**Comment by vnnv01** [comment]
sorry, if I did not explain it correctly.  Whenever we parse a rule, we create a function to do it. 
So If I want to parse a sql 

"Select * from tables"

I will have following rules 

i) select expr  in my case it is "*"
ii) from expr in my case it is "from tables"

I write two different function select_expr and from_expr , similarly , I write multiple functions for each type of sql like create etc. 

After writing a function for each rule, I have 2K lines of code in main.rs. Now I want to split these function parsing the sqls based on rules into different module files. 

like 

i) create.rs
ii) select.rs
iii) insert.rs

All these files will have a separate functions for their own rules in separate files. When I place these functions in a separate files, I get the above error. 

My function field_list looks like this. this is a function for create statement field definitions. 

This function is for the rule field_list in my grammar file. 
``


fn field_list ( p: &Pair<Rule>, default_field_count:&u8) -> (String,String,bool) {

    let p_clone = p.clone();
    let inner_l1 = p_clone.into_inner();
    let mut field_name = String::new();
    let mut data_type = String::new();
    let  field_count:&u8 = default_field_count;
    let mut random_field_list: String = String::new();
    let mut pk_fk_col_flag:bool = false;
    for inner_l2 in inner_l1 {
        match inner_l2.as_rule() {
            Rule::column_name => {
                field_name.push_str(inner_l2.as_str());
                field_name.push_str(" ");
                if *field_count!=0{
                    random_field_list = inner_l2.as_str().to_string();
                }
            },
            Rule::type_name => {
                data_type.push_str(&type_name(&inner_l2));
            },
            Rule::col_constraint => {
                let (constraint_def,flag)= col_constraint(&inner_l2);
                data_type.push_str(&constraint_def);
                data_type.push_str(" ");
                pk_fk_col_flag=flag;
            },
            Rule::COMMA => {
                data_type.push_str(",");
            },
            _=> {
                println!("The rule not matched in fn parse_create_fieldname is {:?} and value is {:?}",inner_l2.as_rule() , inner_l2.as_str());
            }
        }
    }
    let result =  format!("{} {}", field_name, data_type);
    return (result,random_field_list,pk_fk_col_flag);
}``

**Comment by dragostis** [comment]
Well, `Rule` is created where you're invoking the procedural macro:

```rust
mod sql { // Rule will be define inside of this module.
    #[derive(Parser)]
    #[grammar = "sql.pest"]
    pub struct SqlParser;
}

// Now, we can simply access Rule from the module there the derive was used.
use sql::Rule;
```

**Comment by vnnv01** [comment]
Thanks sir. It worked.
