### ISSUE TITLE
How to return error message eagerly

### ISSUE THREAD

**Issue by cjppku** [pest-parser/pest#382]
I want to parse a statement as:
```
statement ::= "return" expression
            | "let" id "=" expression
            | expression
            ;
``` 
I wrote a grammar as
```
statement = {
      "return" ~ expression
    | "let" ~ id ~ "=" ~ expression
    | expression
}
```
What i need is if the parser meets the "return" keyword but failed to parse `expression`, the parser should return an error message eagerly but not continue to parse the next pattern. 

How can I achieve such functionality?

**Comment by dragostis** [comment]
Super interesting question. If `"return"` cannot be an `expression`, then your definition will, in fact, return the error message after it tries the second and third clauses. If `"return"` can be an `expression`, you could simply add `| !"return" ~ expression` to the last clause.

Until now I've assumed that this is a behavior questions. If that's not the case and you're worried about the performance implications, pest tries its best to optimize grammars statically in order not to spend time doing useless work. This particular optimization does not yet apply, but the 3.0 release will focus on a lot of these smaller optimizations.
