### ISSUE TITLE
Question - How to match All chars except Newline?

### ISSUE THREAD

**Issue by mitnk** [pest-parser/pest#392]
Hi, I want to match any chars except the `newline` char, like `[^\n]+` in regex. How could I achieve this in pest?

Here is what I want to parse: https://pest.rs/?bin=ehhze#editor

**Comment by mitnk** [comment]
Got answer from gmatht@Gitter. It's `{ (!NEWLINE ~ ANY)+ }`. Full example [here](https://pest-parser.github.io/?bin=19s1je#editor)

**Comment by birkenfeld** [comment]
@dragostis In general, would it be useful to have a more intuitive "except" syntax? I've needed something like this twice now, and had to think "is this really the best way" each time.

**Comment by mitnk** [comment]
Non-intuitive is not the problem. The problem I think is not fully described in docs/books. Not having a good doc is the main issue of most Rust projects :)

(I want to add a line to the book, but the book repo itself does not have a good readme to me to follow)

**Comment by dragostis** [comment]
I'm sorry that the other repos do not have contributing/building docs. :(

I think pest's level of documentation is good. All the features are there with examples; the issue is that there are no involved examples in the form of tutorials.
