### ISSUE TITLE
Recursion limit causes problems with larger character classes

### ISSUE THREAD

**Issue by bruceg** [pest-parser/pest#41]
I am developing a parser for email headers. One of the rules is designed to match a single character out of a large list:

```
atext           =       ALPHA / DIGIT / ; Any character except controls,
                        "!" / "#" /     ;  SP, and specials.
                        "$" / "%" /     ;  Used for atoms
                        "&" / "'" /
                        "*" / "+" /
                        "-" / "/" /
                        "=" / "?" /
                        "^" / "_" /
                        "`" / "{" /
                        "|" / "}" /
                        "~"
```

Trying to code this directly fails to compile with the "recursion limit reached" error. Reducing the list of characters using ['X'..'Y'] ranges still fails to compile as there are still too many ranges.

Ideally, this would be supported by a single test like [["abcdefg..!#$%&...{|}"]].

**Comment by dragostis** [comment]
This is a good idea. I'll tag this in for the `v0.2.0` release.

Also, the recursion limit issue is solvable by increasing the limit.

**Comment by dragostis** [comment]
Unfortunately, there's no way of pattern matching strings as `tt`s in Rust macros. This leads to two performance issues:

* the need of an iterator which may not get unrolled
* the iterator will have to compute UTF-8 `char` ends

Unless we find a way to solve those two issues, there is no obviously better way to express this. The best current choice would be `[['a', 'b', 'c']]`which is just marginally better than `(["a"] | ["b"] | ["c"])` and which I'd argue decreases readability.

I'm marking the issue as `wontfix`.
