### ISSUE TITLE
Change website editor font to not smash "f" and "l" together

### ISSUE THREAD

**Issue by Yam76** [pest-parser/pest#419]
Type "fl" into the editor, and the two letters will combine into "one" pseudo-letter. This causes the typing cursor to stay in one place after pressing "l", which is not really what one expects when using a code editor.

**Comment by CAD97** [comment]
If you don't want to change the font, [ligatures can be disabled in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures).

**Comment by Yam76** [comment]
Also "|>" leads to an up arrow when typed in the editor.

**Comment by dragostis** [comment]
@Yam76, we could disable ligatures in CSS. Are you interested in writing a patch for that?

**Comment by Yam76** [comment]
@dragostis I would, but I have no idea how :(

**Comment by CAD97** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures
