### ISSUE TITLE
Wide editor

### ISSUE THREAD

**Issue by iago-lito** [pest-parser/pest#421]
I like the [online grammar editor]( https://pest.rs/#editor) much. I use it to draft my little languages.. but it's not very convenient to use because it's small.

Is there a wider editor somewhere else on the internet? Or would it be possible to just make those 3 input frames resizable?

**Comment by lwandrebeck** [comment]
Hello,

There's no other online editor that I know of.
Pest website is available online, so if you can cook a patch to get resizeable frames, @dragostis or some other contributor may merge it.

Best,

**Comment by dragostis** [comment]
I'm very much open to any improvements to the online editor.

**Comment by sbeckeriv** [comment]
CodeMirror does not support a manual resize. The best they have is a full screen mode[1].  I am going to try and fork the rust playground[2] to see how hard it would be to reuse it. The playground has been really useful for me to get going fast.

[1] https://codemirror.net/demo/fullscreen.html
[2] https://github.com/integer32llc/rust-playground
