### ISSUE TITLE
Support UTF8 BOM Signature

### ISSUE THREAD

**Issue by jedmao** [pest-parser/pest#428]
Without support, if a UTF8 file has a BOM at the beginning, I get this Pest error:

```
Error {
  variant: ParsingError {
    positives: [ini],
    negatives: []
  },
  location: Pos(0),
  line_col: Pos((1, 1)),
  path: None,
  line: "\u{feff}a=b",
  continued_line: None
}
```

**Comment by CAD97** [comment]
I believe this is the correct behavior for Pest to take. If your parser wants to accept a bom, it can match it directly. If you don't want to, then you don't.

Alternatively, you can strip the bom before even passing the text to pest.

**Comment by jedmao** [comment]
I'm inclined to agree!
