### ISSUE TITLE
Q: non-rust alternative

### ISSUE THREAD

**Issue by aep** [pest-parser/pest#433]
we're migrating away from rust for portability, but leaving pest behind is pretty sad because it's just so good!

given you probably researched alot, is there maybe a list of inspirations you had?

**Comment by CAD97** [comment]
It all depends on what language you're picking for portability.

[Antlr](https://www.antlr.org/) is what I personally used before, and has targets for Java, C#, Python, JavaScript, Go, C++, Swift, and PHP (and the Java target even has ambiguous tree construction!).

[Tree-sitter](https://tree-sitter.github.io/tree-sitter/) generates a pure C runtime with bindings for Rust, JavaScript (WASM), JavaScript (Node Native Modules), Python, Ruby, and Haskell, and ticks the most boxes of [Matklad's Modern Parser Generator](https://matklad.github.io/2018/06/06/modern-parser-generator.html) goals.

Honestly, you're best off searching for whatever language your using's most popular parsing tools/generators, as most generated and aot-machine-optimized parsing is "fast enough," and ease of use in the target language is important as well.

(Though I'm curious: what platforms are you worried about supporting that you'd need a parser generator for?)

**Comment by aep** [comment]
thank you for your helpful input!

not necessarily portability of the parser. most compilers run on x86 anyway, where rust works fine.
Currently the [zz compiler](https://github.com/aep/zz) is built in rust for that reason, using pest (feel free to add to the list). 

But i'm adding docs and state machine generators now and considering self hosting, depending on what's out there.
