### ISSUE TITLE
Parsing is either very slow or there's an infinite loop?

### ISSUE THREAD

**Issue by losvedir** [pest-parser/pest#436]
I'm working on a parser for the Elixir language and while I'm currently using LALRPOP I wanted to explore using pest for it.

I've run into performance issues. I created a simple repository at [losvedir/pest_slow_example](https://github.com/losvedir/pest_slow_example) that demonstrates a case. You should be able to simply clone the repo, build it in release mode, and then run it, and see it hang.

The grammar is about 70 lines, and the parsed file is about 80 lines, and it hangs seemingly forever (I kill it after a minute or two). I don't think it's an infinite loop, though, because if I remove 25 lines from it, it finishes, but after 30 seconds or so (that file is included in the repo, for reference, but not used).

I'm new to PEG grammars, so it could just be a boneheaded thing I'm doing. If that's the case, are there guidelines about how to construct performant  grammars? I looked through some of the related issues but didn't see anything.

What sort of performance should I expect? My LALRPOP version parses about a 100 files in less than a second it seems, from eyeballing it.

**Comment by CAD97** [comment]
PEG should be, in general, about as performance as a naive recursive descent translation of the specification. (After all, that is, very roughly, what PEG is.) That said, I don't see any obvious pitfalls in your grammar, so it's likely this is rather an issue in the optimizer.

I did confirm the issue on the website playground.

**Comment by CAD97** [comment]
Doing a small amount of minimaztion on the website, the following snippet seems to take way longer to parse than I'd expect:

```elixir
        [ do: {{:., [line: 17], [{:__aliases__, [line: 17], [:Enum]}, :reduce]}, [line: 17], [
          {:arg1, [line: 17], nil},
          {:arg2, [line: 17], nil},
          {:fn, [line: 17], [
            {:->, [line: 17], [
              [{:fn1, [line: 17], nil}, {:fn2, [line: 17], nil}],
              {:if, [line: 18], [
                {{:., [line: 18], [{:__aliases__, [line: 18], [:Map]}, :has_key?]}, [line: 18], [
                  {:fn2, [line: 18], nil},
                  {{:., [line: 18], [{:fn1, [line: 18], nil}, :service_id]}, [line: 18], []}
                ]}
              ]}
            ]}
          ]}
        ]}]
```

So that at least gives a somewhat minimal place to start investigation. cc @dragostis, do you have any time to look at why this may be slow?

**Comment by dragostis** [comment]
The issue here is your definition of repetition with optional comma at the end with causes exponential behavior. Here's a fix:

```pest

WHITESPACE = _{ " " | "\n" | "\r" | "\t" }

file = { SOI ~ expr ~ EOI }
expr = _{ float | integer | atom | binary | list | tuple }


// numbers
integer = { ASCII_DIGIT+ }
float = { ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ }


// binaries (aka strings)
binary = ${ "\"" ~ binary_inner ~ "\"" }
binary_inner = @{ non_quote_char* }


// atoms
atom = ${ atom_literal | ":" ~ atom_identifier }
atom_literal = { "true" | "false" | "nil" | "Kernel" | "Access" }
atom_identifier = { atom_undocumented | atom_unquoted | atom_quoted }
atom_undocumented = {
    "<>"
    | "<<>>"
    | "{}"
    | "++"
    | "||"
    | "&&"
    | "=="
    | "--"
    | "&&"
    | "\\\\"
    | "%{}"
    | "->"
    | "|>"
    | "!"
    | "@"
    | "%"
    | "^"
    | "&"
    | "*"
    | "+"
    | "="
    | "-"
    | "/"
    | "|"
    | "<"
    | ">"
    | "."
}
atom_unquoted = ${ (LETTER | "_") ~ (LETTER | NUMBER | "_" | "@")* ~ ("!" | "?")? }
atom_quoted = ${ "\"" ~ non_quote_char* ~ "\"" }


// lists
list = { "[" ~ (sugar_tuple | expr)? ~ ("," ~ (sugar_tuple | expr))* ~ ","? ~ "]" }
sugar_tuple = { backwards_atom ~ expr }
backwards_atom = @{ atom_identifier ~ ":" }


// tuples
tuple = { "{" ~ expr? ~ ("," ~ expr)* ~ ","? ~ "}" }


// helpers
non_quote_char = {
    !"\"" ~ ANY
    | "\\" ~ ANY
}
```

**Comment by losvedir** [comment]
Ooh, interesting! That does, indeed, do the trick. I'm not sure I totally understand *why* it was a problem, but I guess I know to be more careful with my use of repetition.

Also, for anyone else who comes across this issue, the provided code here allows an invalid parse of, e.g., `[,5]`, but I fixed it by defining `list = { "[]" | "[" ~ expr ~ ("," ~ expr)* ~ ","? ~ "]" }`}`.

Thanks for your help!
