### ISSUE TITLE
pest derive macro is not reproducible

### ISSUE THREAD

**Issue by nagisa** [pest-parser/pest#441]
Using a pest derive macro to generate code will produce non-reproducible results. In turn crates using pest also become non-reproducible and a major pain to deal with.

ref. https://github.com/jturner314/py_literal/issues/14

**Comment by GalAster** [comment]
Yes, the ordering of the built-in rules is random, hope to fix this bug as soon as possible

**Comment by dragostis** [comment]
@GalAster, the newest version of pest_generator should have the fix.
