### ISSUE TITLE
Fuzzit seems to be failing

### ISSUE THREAD

**Issue by CAD97** [pest-parser/pest#443]
cc @dragostis @bookmoons 

https://travis-ci.org/pest-parser/pest/jobs/653730139

It seems that the key isn't being found.

**Comment by dragostis** [comment]
This is weird. The variable is definitely there in Travis. I've just checked it. I'll try to rerun the build.

**Comment by dragostis** [comment]
This seems to be an issue with either Fuzzit or Travis since nothing really changed from the last working build.
