### ISSUE TITLE
Tab character parsed even when not included in WHITESPACE rule?

### ISSUE THREAD

**Issue by zmitchell** [pest-parser/pest#459]
I'm writing a really basic parser that parses sentences. I have the following rules:
```
word = { ASCII_ALPHA+ }
words = { word+ }
WHITESPACE = _{" "}
```

I expect the `words` rule to only match a sequence of (one or more) `word`s that are separated by `" "` characters since that's what I've defined in the `WHITESPACE` rule. It turns out though that this still parses the string `a\tb`, as if `\t` is a valid whitespace character, even though I've defined `WHITESPACE` to only include the `" "` character.

Could you help me understand what I'm missing here?

**Comment by CAD97** [comment]
What you're probably seeing is that pest is parsing a _prefix_ of your input. In `a↹b`, `a` is a valid match for `words`.

If you rewrite your grammar with `words = { word+ ~ EOI }` (End Of Input), then pest will only succeed when parsing the entire input string.

**Comment by zmitchell** [comment]
That was it, thank you!
