### ISSUE TITLE
make PrecClimber support prefix and postfix operators

### ISSUE THREAD

**Issue by mdg** [pest-parser/pest#461]
## Problem

The PrecClimber handles precedence between infix operators, like `a + b * c`, but doesn't handle precedence between prefix or postfix operators, like `-a.b + c`.

## Expectation

The PrecClimber should be able to resolve prefix and postfix operators along with infix operators.

**Comment by mdg** [comment]
I'm looking at taking a shot at this. The plan is to add awareness of prefix or postfix to the [Assoc enum](https://github.com/pest-parser/pest/blob/7dee2a7770daa213b45f88e6af730868f764927a/pest/src/prec_climber.rs#L101-L110) or the [Operator struct](https://github.com/pest-parser/pest/blob/7dee2a7770daa213b45f88e6af730868f764927a/pest/src/prec_climber.rs#L112-L120).

The Operator seems better but not sure if that will cause backwards compatibility issues and maybe the Assoc is less disruptive to the interface.

**Comment by CAD97** [comment]
See also #344, https://crates.io/crates/pratt
