### ISSUE TITLE
unreachable executed on pest.rs editor

### ISSUE THREAD

**Issue by erayerdin** [pest-parser/pest#462]
I am new to PEG. I wanted to test on pest.rs. However, it seems it throws an error. The site loads wasm module names `pest_site`. However, whenever I type on input, it throws `RuntimeError: unreachable executed`. With details:

```plain
__rust_start_panic https://pest.rs/pest-site.wasm:354742
    rust_panic https://pest.rs/pest-site.wasm:354214
    h51f1c855dfa04d94 https://pest.rs/pest-site.wasm:353469
    h728aed66c815f8d0 https://pest.rs/pest-site.wasm:353157
    rust_begin_unwind https://pest.rs/pest-site.wasm:353033
    h59066e1e00f1980f https://pest.rs/pest-site.wasm:364458
    h2629fd904a66558c https://pest.rs/pest-site.wasm:364242
    h8ebf157918e4c235 https://pest.rs/pest-site.wasm:34509
    h0353d924de912f2e https://pest.rs/pest-site.wasm:11798
    dyncall https://pest.rs/pest-site.js:425
    __extjs_2034053b7b6771271a2dad3e5416b045a74488a1 https://pest.rs/pest-site.js:506
```

Maybe my grammar is wrong? I don't know.

**Comment by CAD97** [comment]
The playground seems to be working on my end.

What browser are you using, and what input are you seeing hit an unreachable?

**Comment by erayerdin** [comment]
I have switched to logos so I'm afraid I cannot give further information apart from my browser, it was Firefox. Feel free to close the issue.
