### ISSUE TITLE
Outdated Unicode version

### ISSUE THREAD

**Issue by rafael-patronilo** [pest-parser/pest#466]
I noticed a rule in a project I contributed to was giving an error on a character I expected it to accept. I have identified this problem to be related to the fact this character was added in [Unicode 12.0.0](https://unicode.org/versions/Unicode12.0.0/) (2019) and [categories.rs](https://github.com/pest-parser/pest/blob/master/pest/src/unicode/category.rs) was last updated to Unicode version [11.0.0](https://unicode.org/versions/Unicode11.0.0/) (2018). Unicode's latest version at the point I'm writing this issue is [13.0.0](http://www.unicode.org/versions/Unicode13.0.0/).

I have looked at the issues and located #311 , am I right to assume Unicode updates are pending on this issue?

PS: I would very much like to contribute to the solving of this issue however I'm still very new in Rust (first year) and I'm still in the 1st year of college (Computer Science) although I have around 5 years of programming as a hobby. Therefore, I am unsure if I have the skills required to solve issue #311 correctly.

**Comment by CAD97** [comment]
No need specifically to address #311 to update the Unicode version, just need to update the actual generated files.

That should be as simple as figuring out what files were generated and using ucd-generate to regenerate them.

**Comment by lorenzleutgeb** [comment]
Since #368 was merged, could you please clarify or close?

**Comment by tomtau** [comment]
I think it can be closed. There's now unicode 14 though: https://github.com/pest-parser/pest/pull/574/files

**Comment by tomtau** [comment]
I think it can be closed. There's now unicode 14 though: https://github.com/pest-parser/pest/pull/574/files
