### ISSUE TITLE
[Question] Is it possible to modify grammar at runtime?

### ISSUE THREAD

**Issue by Geobert** [pest-parser/pest#471]
Hi, 

I don't know if the issue tracker is the appropriate place to ask question, pardon me if it isn't :)  

I have a this grammar rule:
```
reason = { "#" ~ ANY* }
```
 but I'd like the starting character to be customizable at runtime. 

Is there a way to achieve this?

Thanks!

**Comment by CAD97** [comment]
This isn't possible within pest's structure.

Pest precompiles your grammar to what is effectively a "jump table;" it knows that given a current state, if it sees character X, go to state Q. This makes the generated code fast, but inflexible.

If complied code size isn't too much of an issue, the easy way to get this behavior would be just to compile multiple versions of your grammar with the different configuration options, and then choose which grammar to run based on runtime options. If the number of variables is relatively small, this is tractable, if suboptimal.

**Comment by Geobert** [comment]
I see, thank you very much for your answer!

**Comment by stefnotch** [comment]
For the record, alternative workarounds if one has a large number of grammars are also possible
- Figure out how to write a general grammar, and then manually check the rules after parsing
- Compile a grammar at runtime, and run it with pest vm. See also https://github.com/pest-parser/pest/issues/432
