### ISSUE TITLE
how to implement action-like feature similar to Yacc in pest.

### ISSUE THREAD

**Issue by erihsu** [pest-parser/pest#474]
Hi, 
I am new to pest and I wonder if I can implement action feature in pest rule such as below in yacc
`version:  VERSION_KEYWORD { do something; }`

Any alternative suggestions is also really helpful.

**Comment by dragostis** [comment]
The selling point of pest is to separate grammar from semantic actions, in order to preserve grammars readable and reusable. Semantic action is something you can do by using the [`Pairs` API](https://docs.rs/pest/2.1.3/pest/iterators/struct.Pairs.html).
