### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by GiraffeKey** [pest-parser/pest#477]
https://isitup.org/pest.rs

https://www.isitdownrightnow.com/pest.rs.html

**Comment by dragostis** [comment]
Working on it.

**Comment by yonkeltron** [comment]
Can confirm this from my company's network as well as from my personal home connection. Chrome tells me it's an `DNS_PROBE_FINISHED_NXDOMAIN` which isn't a great sign.

**Comment by bitbegin** [comment]
if you need to use the pest editor, visit `https://bitbegin.github.io/pest-rs/`

**Comment by dragostis** [comment]
@yonkeltron, unfortunately, the person who is administrating the website got sick after making the (failed) payment and I couldn't access the account. Hopefully they'll get better and I'll get the domain back.
