### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Keruspe** [pest-parser/pest#485]
Hi,

A new release would be appreciated, to avoid building sha-1 and its dependencies two times.
The dependency was updated 4 months ago but there hasn't been a release since then

**Comment by dragostis** [comment]
Sure thing, but I'd first like to have CI back up after it's migrated on GitHub Actions. Blocked by #482.

**Comment by nilsmartel** [comment]
anyone still working on this?

**Comment by klensy** [comment]
Hi, any update on this, almost year? `pest_meta` already updated sha-1 to 0.9 version in master, but isn't released minor version update, thus preventing removing duplicates (and from rust compiler repo too).

**Comment by Keruspe** [comment]
Any news on this? sha-1 is now even at 0.10.

What's blocking a new release?

**Comment by CAD97** [comment]
> What's blocking a new release?

Now that release permission is granted to the admin group, just time unfortunately 😅
It's on my list, but it's not easy to find time to just sit down and go through the release checklist (which was never actually written down, so that makes it more complicated).

**Comment by klensy** [comment]
Hello there again ;-)

**Comment by MarijnS95** [comment]
Anyone still looking into making a new release for at least `pest-meta`? It'd be great to get rid of the older `sha-1` release which is in fact only used in `[build-dependencies]`, whereas `build.rs` is not even shipped in the released crate :no_mouth: 

At the same time `build.rs` depends on a locally built binary from this crate in `../target/debug/pest_bootstrap`, making projects unable to simply use a git reference to the master branch with `[patch.crates-io]`.

**Comment by tomtau** [comment]
It's here: https://github.com/pest-parser/pest/discussions/669

**Comment by nilsmartel** [comment]
I am beyond surprised but also very glad and happy.
You're doing the lords work here man :)
