### ISSUE TITLE
[Question/Feature Request] using Rust's cargo feature in grammar

### ISSUE THREAD

**Issue by Geobert** [pest-parser/pest#488]
I don't know if it's possible but I don't think so.

I'd like to modify the grammar according to the feature active at compilation time. Like adding more rules to support a feature and not having them (hopefully shrinking the code size) when not used.

Is that possible?

**Comment by SkiFire13** [comment]
I don't think you can use features flag in the grammar itself, however you should be able to create multiple grammars and use a feature flag to select which one to use at compile time with `cfg_attr`.

**Comment by Geobert** [comment]
Good idea!
