### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ClementNerma** [pest-parser/pest#499]
Hi there!

I've been using Pest for a bit more than a year now, and given the recent activity of the repository (~ 65 commits in 2 whole years), I was wondering if this project was still maintained?

If it's not, I think it would be nice to indicate in the README that it's actively looking for maintainers, this way the project could be maintained by another person or group of persons.

Pest is a really awesome project, and it'd be unfortunate to let it abandonned now that it's gone this far ;)

**Comment by CAD97** [comment]
See also https://github.com/pest-parser/pest/issues/496 and stuff linked from there

**Comment by ClementNerma** [comment]
> See also #496 and stuff linked from there

Indeed, I totally forgot that issue 😄 
Thanks
