### ISSUE TITLE
Getting "panic message is not a string literal" from Rust 2021

### ISSUE THREAD

**Issue by applegrew** [pest-parser/pest#505]
When using Rust 2021 I am getting the following warning wherever `parses_to!` is used.

    warning: panic message is not a string literal
      --> src/parser/unit_tests.rs:11:5
       |
    11 | /     parses_to! {
    12 | |         parser: JsParser,
    13 | |         input: "10",
    14 | |         rule: Rule::numeric_literal,
    ...  |
    21 | |         ]
    22 | |     };
       | |______^
       |
       = note: this is no longer accepted in Rust 2021
       = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by applegrew** [comment]
I had to use `#[allow(non_fmt_panic)]` to turn off this warning.

**Comment by nirvdrum** [comment]
I'm using Rust 2018 and I'm seeing the warning as well. It started with Rust 1.51.0, I think.

**Comment by CAD97** [comment]
Yep, this is a new rustc warning that we didn't realize was a problem in the emitted code before.

**Comment by CAD97** [comment]
(I won't have the bandwidth to make a PR to fix this anytime soon, likely, but I can approve a PR if someone else sets it up. I believe @01mf02 [found where the issue needs fixing](https://github.com/pest-parser/pest/pull/498#issuecomment-812881078).

**Comment by CAD97** [comment]
This should be fixed by #507.

**Comment by MarinPostma** [comment]
this fixed by #507

**Comment by nirvdrum** [comment]
If not too much of a problem, can we please get this in a release? I can continue to use `#![allow(non_fmt_panic)]`, but this seems like the sort of thing that will be unexpected by new users.
