### ISSUE TITLE
Keyword being a prefix of an identifier

### ISSUE THREAD

**Issue by kjagiello** [pest-parser/pest#506]
First of all, thanks a lot for this project! I found it very useful!

I have some trouble figuring out how to define a rule for an identifier that should not be a keyword. Sounds probably cryptical, so I'll give an example instead.

#### Grammar:
```
identifier = { !keyword ~ ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }
keyword = { "foo" }
```

#### Input:
```
foobar
```

#### Output:
```
 --> 1:1
  |
1 | foobar
  | ^---
  |
  = unexpected keyword
```

I want `foobar` to be considered a valid identifier and `foo` to be considered an invalid one. I looked through docs and the list of projects using pest and they followed the same pattern for the identifiers vs keywords as mine, so I'm a bit confused if it is even possible to express this using pest? Thanks in advance!

**Comment by CAD97** [comment]
The trick is a negative lookahead as part of your keyword rule. Thinking about it, the keyword `foo` is defined roughly as "the string `foo`, so long as it is not immediately followed by any character valid in an identifier. Thus,

```rust
grammar = { (keyword | ident)+ }

WHITESPACE = { WHITE_SPACE } // I'm sorry this is how you do this, it's my fault
ident = @{ ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }
keyword = @{ "foo" ~ !ASCII_ALPHANUMERIC }
```

(This uses PEG's ordering to prefer keyword over ident.)

**Comment by kjagiello** [comment]
Ah, of course, this makes perfect sense! Thanks a lot for your explanation! Have a good one!
