### ISSUE TITLE
Parse inner text with compulsory surrounding brackets

### ISSUE THREAD

**Issue by bartekupartek** [pest-parser/pest#518]
Is it possible to make closing bracket required if we have starting bracket before new line?

Grammar:
```
ident = { (!("[" | "]") ~ ANY)+ }
entity = { ("[" ~ ident ~ "]") }
```
Input:
```
[Person]
skiptext
```
Output:
```
- entity > ident: "Person"
```

If I remove closing bracket:
```
[Person
skiptext
```
the output error shows starting bracket:
```
 --> 1:1
  |
1 | [Person␊
  | ^---
  |
  = expected entity
```
I'd like to show error on the end of line, is it possible with pest?
Can I get directly `entity > "Person"` in output when syntax is correct?

**Comment by CAD97** [comment]
> I'd like to show error on the end of line, is it possible with pest?

Pest's error reporting uses the named rules. So if you have `entity = { ("[" ~ ident ~ "]") }`, it points at the front of the place where the entity is expected and says that an entity was expected.  If you have `entity = { (open_bracket ~ ident ~ close_bracket) }`, it will point at the end and say expected `close_bracket`. Unfortunately for your specific case, Pest only mentions non-silent rules, so you would have to include the node in the emitted parse tree to get it in the error report.

> Can I get directly entity > "Person" in output when syntax is correct?

With some tricks, yes:

```
entity_outer = _{ "[" ~ entity ~ "]" }
entity = { _ident }
_ident = _{ (!("[" | "]") ~ ANY)+ }
```

but in my experience it's easier to write the grammar in a simple way, and then process the parse tree into AST more fit for consumption in later passes.

**Comment by bartekupartek** [comment]
Thank you it improved a lot my code, but I'm still struggling with this part 
>  If you have entity = { (open_bracket ~ ident ~ close_bracket) }, it will point at the end and say expected close_bracket

when I remove closing bracket it points opening bracket and vice versa, or it is including bracket of next entity, it would be hard to fix by code, can I fix it by grammar?

When I remove opening bracket
```
Person]
skiptext
[`Birth Place`]
```
parse error shows:
```
 --> 1:7
  |
1 | Person]␊
  |       ^---
  |
  = expected EOI
```
when closing bracket is removed:
```
[Person
skiptext
[`Birth Place`]
```
The parser error is:
```
 --> 3:1
  |
3 | [`Birth Place`]␊
  | ^---
  |
  = expected close_bracket
 ```
My current grammar:
```
open_bracket = { "[" }
close_bracket = { "]" }

entity_outer = _{ (open_bracket ~ entity ~ close_bracket) }
entity = { _ident }
_ident = _{ (!("[" | "]") ~ ANY)+ }
```

**Comment by bartekupartek** [comment]
I'm not sure if my reported issue is actually a bug, I'd like to determine entity from opening to closing brackets but it seems this grammar doesn't allow me to define such expression but I might be wrong.

**Comment by bartekupartek** [comment]
I seems it's working with separable brackets definitions 🎉  I found that `(!("[" | "]") ~ ANY)+` could be replaced by `ASCII_ALPHANUMERIC*`, thank you for your patience 🙏
