### ISSUE TITLE
PrecClimber prefix/suffix support

### ISSUE THREAD

**Issue by CraftSpider** [pest-parser/pest#526]
It would be nice if `PrecClimber`, or a variant of it, could have support for prefix/suffix operators. Currently it requires copying over the code and implementing it yourself, which while possible, increases the chance for bugs and the difficulty on the library user.

Possible API for a new climber:
- Add a new operator type, `Infix`, `Prefix` and `Suffix` or similar
- Add `prefix` and `postfix` closure parameters to `climb`
- `Prefix` doesn't expect an shs
- `Postfix` doesn't expect an rhs

With this new climber, one could easily parse a syntax roughly like
```
expr = {
    prefix_ops* ~ target ~ suffix_ops* ~ (infix_op ~ prefix_ops* ~ target ~ suffix_ops*)*
}
```

**Comment by tomtau** [comment]
this is now possible in `PrattParser`: https://pest.rs/book/precedence.html
