### ISSUE TITLE
[Suggestion] Make PrecClimber::climb panic if it can't find an operator

### ISSUE THREAD

**Issue by Technohacker** [pest-parser/pest#570]
While building the expression parser for my grammar, I was stumped on why the climber didn't progress beyond one expression sub-unit. Turns out I had forgot to make my operator catch-all rule silent, which caused the climber to break out on [this line](https://github.com/pest-parser/pest/blob/master/pest/src/prec_climber.rs#L354)

Making this either an explicit panic (for a static operator set) or an Error return (for a dynamic operator set) may make more sense in alerting to a bad grammar, since it's unexpected for the parser to ask for an operator beyond those provided to the climber

This may be a breaking change since the climber is part of the public API

**Comment by tomtau** [comment]
`PrecClimber` is deprecated, there's a `PrattParser` now -- not sure if this issue still applies to it, but feel free to re-open the issue if it does.
