### ISSUE TITLE
Projects using Pest

### ISSUE THREAD

**Issue by yoav-lavi** [pest-parser/pest#587]
Hey, I'm using Pest over in [Melody](https://github.com/yoav-lavi/melody)! ([grammar](https://github.com/yoav-lavi/melody/blob/main/crates/melody_compiler/src/ast/grammar.pest))
Thanks for making Pest!

**Comment by tomtau** [comment]
@yoav-lavi feel free to open a PR to add it to README along with https://github.com/pest-parser/pest/pull/567

**Comment by tomtau** [comment]
added in https://github.com/pest-parser/pest/pull/567
