### ISSUE TITLE
[BUG] pest does not take into consideration that an expression can be followed by characters used in the grammar

### ISSUE THREAD

**Issue by Keaudes** [pest-parser/pest#604]
Grammar:
`text = { ("a" ~ "_")+ ~ "a" }`
Input:
`a_a_`
Output:
```
 --> 1:1
  |
1 | a_a_
  | ^---
  |
  = expected text
```

It seems the parser's thought process is as follows:

- "a_" found twice
- this is not followed by "a", therefore parsing failed

This is of course not the desired output, since the parsing result can also just be:

- "a_" found once
- this is followed by "a", correct

where the underscore after the last 'a' is not seen as part of the parsing result.

So, the desired output would be:
`- text: "a_a"`

pest does not attempt to parse the second "a_" as an "a", so using the second option. It does not take into consideration that an expression can be followed by characters used in a rule.

After experimenting a bit, I've found that:

Grammar:
`text = { "ab" ~ "d" | "ab" }`
Input:
`abc`
Output:
`- text: "ab"`

this in fact does work as expected, which is odd, seeing as this is more or less the same problem as before.

**Comment by CAD97** [comment]
This is how PEG functions. PEG is a greedy recursive descent parser; once input is consumed, it is not backtracked except at a `|` alternation of rules.

`("a" ~ "_")+ ~ "a"` is equivalently `("a" ~ "_") ~ ("a" ~ "_")* ~ "a"`. The behavior you actually want is `"a" ~ ("_" ~ "a")*`.

Writing a PEG grammar is much closer to declaratively writing a recursive descent parser than writing a formal grammar.

`"ab" ~ "d" | "ab"` translates to roughly

```rust
let _reset = input;
if ("ab", input) = input.split(2) {
    if ("d", input) = input.split(1) {
        return true;
    }
}
input = _reset;
if ("ab", input) = input.split(2) {
    return true;
}
return false;
```

`("a" ~ "_") ~ ("a" ~ "_")* ~ "a"` translates to roughly

```rust
if ("a", input) = input.split(1) {
    if ("_", input) = input.split(1) {
        loop {
            let _reset = input;
            if ("a", input) = input.split(1) {
                if ("_", input) = input.split(1) {
                    continue;
                }
            }
            input = _reset;
            break;
        }
        if ("a", input) = input.split(1) {
            return true;
        }
    }
}
return false;
```

There are optimizations that can be done, but this is the semantics of the PEG grammar.
