### ISSUE TITLE
Get start and end of the rule in `Error`.

### ISSUE THREAD

**Issue by muppi090909** [pest-parser/pest#611]
How do I get the start and end of a rule from an `Error`.
For example
grammar.pest
```
WHITESPACE = _{" "}
hello = {SOI ~ "hello" ~ WHITESPACE ~ "world" ~ EOI}
```
main.rs
```
use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "grammar.pest"]
struct MyParser;

fn main() {
    let output = MyParser::parse(Rule::hello, "jello world").unwrap_err();
    println!("{}", output)
}
```
Instead of seeing where the parser stopped I want to see how much it expected as in show 0 to 4 as wrong.

**Comment by gimbles** [comment]
Probably better to ask this in a Discussion rather than an issue.

**Comment by muppi090909** [comment]
Conversation moved to [discussion](https://github.com/pest-parser/pest/discussions/612)
