### ISSUE TITLE
Breaking changes in latest release

### ISSUE THREAD

**Issue by alice-i-cecile** [pest-parser/pest#672]
The most recent minor version release has breaking changes in it, which appears to have broken [tera](https://github.com/Keats/tera).

This in turn [broke our CI](https://github.com/bevyengine/bevy/pull/5484); see [this failed run](https://github.com/bevyengine/bevy/actions/runs/2761136096).

**Comment by alice-i-cecile** [comment]
Upstream issue: https://github.com/Keats/tera/issues/739

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by regar42** [comment]
I believe the culprit is here: https://github.com/pest-parser/pest/commit/723d00644e82ebe673a7c7903fd4d5038d46ab77

**Comment by mockersf** [comment]
I tried fixing the path in Tera, a lot of other errors appeared after
```
error: could not compile `tera` due to 379 previous errors; 1 warning emitted
```

**Comment by MarijnS95** [comment]
@regar42 I've also "bisected" this to be caused by https://github.com/pest-parser/pest/pull/522; that change doesn't account for modules/folders deeper than `$CARGO_MANIFEST_DIR/src/<the file>.pest` it seems.

**Comment by regar42** [comment]
Could we maybe yank the release 2.2.0 until this is fixed? :blush:

**Comment by tomtau** [comment]
> Could we maybe yank the release 2.2.0 until this is fixed? 😊

It's yanked now.

**Comment by MarijnS95** [comment]
@tomtau Shall #522 be reverted so that `2.3.0` can be published? It's both a breaking change and something that I don't see how to fix in a trivial way.

**Comment by tomtau** [comment]
@MarijnS95 yes: https://github.com/pest-parser/pest/pull/673
Could you try to test to use the version with the reverted commit if everything else works as before?
```
pest = { git = "https://github.com/tomtau/pest.git", rev = "39595d56729c6613e5792e0bf3e6c11d9b89d03d" }
```
I'm not sure if there are any other sneaky breaking changes.

**Comment by MarijnS95** [comment]
@tomtau Tested, fixes the errors again!

Note that I couldn't use your branch as a patch as it started complain about `bootstrap`, had to check it out locally to make it bootstrap first :)

**Comment by alice-i-cecile** [comment]
Thank you very much for the prompt fix!

**Comment by SafariMonkey** [comment]
> The most resilient choice seems to be committing the generated file(s) and updating it in a test (this is what r-a does), but our bootstrapped parser changes much more frequently than r-a's generated AST types, so doing so would cause us to run into significantly more conflicts from committing the generated file.

This may not help for automated merges on GitHub etc., but looking into solutions I found an approach that can ease the pain of merging generated files during local dev:

https://www.charpeni.com/blog/use-custom-merge-driver-to-simplify-git-conflicts

Pest is used by a lot of popular crates (good job!), and having a transitive dependency sometimes fail to compile and require manual intervention (or trying again and again until after 15 minutes randomly worked, according to a friend) isn't ideal. I hope you can find a relatively painless solution!
