### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ethindp** [pest-parser/pest#714]
**Describe the bug**
The pest.rs website is down. At first I thought it was my DNS, but it isn't.

**To Reproduce**
Just try going to pest.rs.

**Expected behavior**
I should be able to visit the website.

**Additional context**

**Comment by tomtau** [comment]
@ethindp thanks for the report. It seems the domain expired. For the moment, the website should be available on [pest-parser.github.io](https://github.com/pest-parser/pest-parser.github.io).

CC @CAD97 @dragostis .

**Comment by tomtau** [comment]
I updated the website link to [pest-parser.github.io](https://pest-parser.github.io/) for the moment.

I had a quick email exchange with @dragostis -- the domain registration costs were being covered by @dragostis which doesn't seem like a solution that will work in the long term, so the suggestion was to crowdfund it: https://github.com/sponsors/pest-parser

**Comment by ethindp** [comment]
The problem is that the pest-parser.github.io domain redirects you to pest.rs.

**Comment by tomtau** [comment]
> The problem is that the pest-parser.github.io domain redirects you to pest.rs.

I removed the CNAME file: https://github.com/pest-parser/pest-parser.github.io/commit/fccb7dab4fe0fe170dd18da4f3d5ccfe5dac3af4 so it shouldn't redirect now -- at least it doesn't in my browser. Can you try clearing your browser cache or opening it in an incognito / private tab?

**Comment by ethindp** [comment]
It works for me now. Thanks.

**Comment by tomtau** [comment]
it should be back up now: https://pest.rs
