### ISSUE TITLE
Add non-consuming Pattern for Matcher

### ISSUE THREAD

**Issue by W4RH4WK** [pest-parser/pest#74]
Hey, I am using pest to build the frontend of a toy compiler and really like the simplicity and fact that no external tool is required. Really good work!

I am still getting my head around processing the queue of tokens and would like you to think about adding a pattern for matchers which do not advance the parser's `queue_index`.

Say I have a function for processing an `expression`, it reads an `expression` token (+ following) and returns me an `ast::Node`. At some other point I'd like to match a comma-separated sequence of `expression`s. This would be somehow similar to your `Letter`, `Word`, `Sentence` example.

So I'd create a new matcher for the sequence of `expression`s, but I cannot utilize the original `expression` processing function since the new rule would need to consume one `expression` token.

```
process! {

    parse_expression(&self) -> ast::Node<ast::Expression> {
        // matches on `expression` and related tokens
    }

    parse_expressions(&self) -> LinkedList<ast::Node<ast::Expression>> {
        //
        //  .-- ( need to match on expression, but this consumes a token which is
        //  |   ( needed in `parse_expression`. 
        //  V
        (_: expression, expr: parse_expression(), mut tail: parse_expressions()) => {
            tail.push_front(expr);
            tail
        },

        () => LinkedList::new(),
    }

}
```

I could work around this by adding a wrapper rule for `expression` so I can match on it without consuming the actual expression. But I think a non-consuming pattern would be a useful extension and solve the problem in a better way.

**Comment by dragostis** [comment]
I agree that this is a useful addition. Will probably add it to the `v0.4.0` branch rather soon. Still have to find a syntax that would work and not be very confusing.

**Comment by W4RH4WK** [comment]
Just as an idea for the syntax, how about prefixing the rule with an `&`. Thinking about it as taking a reference to what is in the queue, but not moving it out of the queue.

```
    parse_expressions(&self) -> LinkedList<ast::Node<ast::Expression>> {
        // here the expression token is moved out of the queue
        (_: expression) => {...},

        // expression token remains in queue
        (_: &expression) => {...},
    }
```

It would still be compatible with prefixing the identifier with an `&`.

```
    parse_expressions(&self) -> LinkedList<ast::Node<ast::Expression>> {
        (expr: &expression) => {...},

        (&expr: &expression) => {...},
    }
```

**Comment by Keats** [comment]
just wanted that exact feature right now as well

**Comment by Phrohdoh** [comment]
Looking at this again... shouldn't this be done in `grammar!` with `{ &foo }`?
