### ISSUE TITLE
Reliance on SHA1 library causes dependents to be flagged as unsafe

### ISSUE THREAD

**Issue by jeramyRR** [pest-parser/pest#763]
Even though SHA1 is only used in meta/build.rs, it's causing dependent projects to be flagged in some build systems as unsafe to use.  I'm happy to submit a PR to switch out SHA1 for SHA2, or whatever preferred algorithm, but I'm not sure completely about when and where the file hash comes in to play.

Please see https://sha-mbles.github.io/ for more information on why SHA1 is no longer considered safe to use.

**Comment by tomtau** [comment]
fixed in https://github.com/pest-parser/pest/pull/764
