### ISSUE TITLE
Pairs#move_cursor is slow down iter

### ISSUE THREAD

**Issue by huacnlee** [pest-parser/pest#784]
Hi @tomtau,

I am very sorry about that. 😥

I have found `Pairs#iter` performance issue when we merged #754.

Because when we iter pairs, each iter next will called `Position#line_col` once to move cursor. That will slow down the iter . 

Especially that, in sometimes we just need get a little pair's line,col, not all of pairs. So to do this is not value of money.

By my test:

```rs
fn bench_pairs_iter(c: &mut Criterion) {
    let data = include_str!("data.json");

    fn iter_all_pairs(pairs: pest::iterators::Pairs<autocorrect::Rule>) {
        for pair in pairs {
            iter_all_pairs(pair.into_inner());
        }
    }

    c.bench_function("nested iter", |b| {
        let pairs = autocorrect::JsonParser::parse(autocorrect::Rule::item, &data).unwrap();

        b.iter(move || iter_all_pairs(pairs.clone()));
    });

    c.bench_function("flatten iter", |b| {
        let pairs = autocorrect::JsonParser::parse(autocorrect::Rule::item, &data).unwrap();

        b.iter(move || {
            for _pair in pairs.clone().flatten().into_iter() {
                // do nothing
            }
        });
    });
}
```

```
nested iter                             time:   [258.27 µs 260.05 µs 262.64 µs]
nested iter (fast-line-col)             time:   [14.943 µs 14.963 µs 14.993 µs]
flatten iter                            time:   [2.0367 µs 2.1104 µs 2.2144 µs]
```

> In a large files (or have a lot of pairs, For instance: enabled `WHITESPACE`, each spaces will a pair item), iterate all pairs may take a long time than before.

So we need decide to how to do, remove it or find some solution to fix that.

**Comment by tomtau** [comment]
How about feature-guarding it? It'll be disabled by default -- if someone needs it, they can enable that feature?

**Comment by huacnlee** [comment]
Or change API like peekable or flatten, to make a special iterator?

```rust
pairs.locatable().next()
```

This will make a `LocatablePairs`, then prepare `line, col` only work in it.

**Comment by tomtau** [comment]
@huacnlee yes, that's perhaps simpler in the sense that the combination of possible feature flags doesn't increase more. Would you like to open a PR with this fix?

**Comment by huacnlee** [comment]
I have trying to find other way to solve it.

**Comment by huacnlee** [comment]
@tomtau To see my new PR, I find a new way to solve it.

https://github.com/pest-parser/pest/pull/785
