### ISSUE TITLE
Multiple grammars not always recompiled

### ISSUE THREAD

**Issue by jayhale** [pest-parser/pest#789]
**Describe the bug**
When using multiple grammars as described in #758:

```rust
use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "base.pest"]
#[grammar = "core.pest"]
struct SplitGrammarParser;
```

The parser is only recompiled with new grammars from both files when the last grammar is changed.  I.e., changes to only `base.pest` aren't captured in debug builds until something in `core.pest` changes.

**To Reproduce**

- Create a simple grammar split across two files
- Use derive as above
- Experiment with changes in either or both grammar files (e.g., with `cargo watch -x test`)

**Expected behavior**

A change to any grammar should cause the parser to recompile with updates from all grammar files.

**Comment by tomtau** [comment]
CC @huacnlee
