### ISSUE TITLE
Request: Allow leading `~` (since leading `|` is already allowed)

### ISSUE THREAD

**Issue by KSXGitHub** [pest-parser/pest#814]
I want to be able to do this:

```pest
my_rule = {
   ~ expression_1
   ~ expression_2
   ~ expression_3
   ~ expression_4
}
```

Sadly, leading `~` is currently not allowed, so I have to settle for an uglier version.

**Comment by NoahTheDuke** [comment]
See #553 for discussion about why it isn't allowed.

**Comment by tomtau** [comment]
@NoahTheDuke should this issue be closed?

**Comment by NoahTheDuke** [comment]
Sure. If someone else raises the question, we can maybe reopen the discussion about whether including this is a good idea.
