### ISSUE TITLE
validator not reporting an error for indefinite parsing

### ISSUE THREAD

**Issue by jiftoo** [pest-parser/pest#830]
Hello. I hope this issue adds value to the other hang/timeout issues that are open already.

```rust
// not when no '!reserved |'
ident    = @{ !reserved | !(ASCII_DIGIT) ~ ('a'..'z' | 'A'..'Z' | "_" | '0'..'9')+ }
// not when reserved = {""}
reserved =  { " " }

// coalesced version from og. code
b_op = { "." }

expr_un = _{ term_un ~ (b_op ~ term_un)* }
term_un = _{ (ident) | "(" ~ expr_un ~ ")" }
// crashes!
expr_post = @{ (expr_un)* ~ b_op }

WHITESPACE = _{ (" " | NEWLINE)  }
```

The following input causes the hang:
```plaintext
if (
```

The debugger shows this:
```plaintext
--> 1:1
  |
1 | if (a) {
  | ^---
  |
  = parsing ident
```

Please note that the rule `ident`, by itself, doesn't cause a hang, and instead finishes normally:
```
- ident: ""
```

No other rule causes issues.

**Comment by Tartasprint** [comment]
The grammar you are describing has rules that do not consume anything:

- `ident    = @{ !reserved | ...` in case the input starts with something else than a space
- as a consequence `term_un` in case the input starts with something else than a space
- then `expr_un` in case the input  starts neither by a space nor by a `b_op` (".")

So when `expr_post` is applied to an input starting neither by a space nor by a dot,  the `*` consumes nothing indefinitely and gets stuck.

I'm new here but from what I understand, one of the steps in reading the grammar is validation (done if I'm not mistaken in meta/src/validator.rs).  The validation step should catch and report this kind of errors. There are two validation steps that seem to aim to catch this error, `pest_meta::validator::is_non_progressing` and `pest_meta::validator::is_non_failing`; but neither of them catches the error.

I would like fix this bug, but I don't know what those two step are really meant to do, if it is the right place to do it.
I'm not sure why those two steps are separate, what is the difference between "failing" and "not progressing" ?

**Comment by tomtau** [comment]
> I'm not sure why those two steps are separate, what is the difference between "failing" and "not progressing" ?

@Tartasprint based on my understanding from reading the test cases and this older PR: https://github.com/pest-parser/pest/pull/259 , the difference is the following:

- non-progressing == it loops forever
- non-failing == it can terminate, but it is always succeeding / consuming tokens in one place, such as in choices, the non-failing branch always succeeds for possible inputs, while the other branches are "dead code" / redundant / never done because of that
