### ISSUE TITLE
Add example for negation operator

### ISSUE THREAD

**Issue by indeyets** [pest-parser/pest#93]
`!a` doesn't have any practical examples. it should have one.

It would be useful to show `!["}"] ~ any` pattern or something similar ("anything but delimiter is allowed")

**Comment by dragostis** [comment]
This should be tackled in the [tutorial](https://github.com/pest-parser/pest/issues/123).

**Comment by jstnlef** [comment]
Moved this to https://github.com/pest-parser/book/issues/8
