### ISSUE TITLE
Add link to documentation for custom PEG syntax

### ISSUE THREAD

**Issue by sunjay** [pest-parser/pest#95]
I wanted to use this library so I looked up "PEG syntax". The first two results were the Wikipedia article and [this guide](https://github.com/PhilippeSigaud/Pegged/wiki/PEG-Basics). The Wikipedia article is largely unhelpful so I read the guide and then moved on to your library.

Reading the documentation, it looks like you have some examples, but not much description of the syntax or what you're doing in each piece of code. Your syntax looks quite different from the standard PEG format. I did eventually find the syntax documented on the [grammar macro](http://dragostis.github.io/pest/pest/macro.grammar.html). It would be nice if you could link it at the beginning of the guide so we know to look there.

Examples of questions I had while reading the guide:
- What is `~`? Does that denote sequences?
- Why are all the literals in square brackets? E.g. `["-"]`
- It looks like `impl_rdp` implements a parser called Rdp. That isn't talked about anywhere in the guide or in the docs. What if I don't want my parser to be called `Rdp`? Can I change the name somehow?

**Comment by dragostis** [comment]
Thank you for taking time to write this thoughtful issue. I think that maybe the long example at the start of the library might not be the best introduction. Maybe the documentation should be split up like this:

* why PEG?
* pest syntax
* how peste works behind the scenes
* shorter example
