### ISSUE TITLE
Comment does not work as expected if not atomic

### ISSUE THREAD

**Issue by sunjay** [pest-parser/pest#97]
This works:
```rust
comment = _{
    ( (["//"] | ["#"]) ~ (!(["\r"] | ["\n"]) ~ any)* ~ (["\n"] | ["\r\n"] | ["\r"] | eoi) ) |
    (["/*"] ~ (!(["*/"]) ~ any)* ~ ["*/"])
}
```

This does not:
```rust
comment = { block_comment | line_comment }
line_comment = _{ ["//"] ~ (!(["\r"] | ["\n"]) ~ any)* ~ (["\n"] | ["\r\n"] | ["\r"] | eoi) }
block_comment = _{ ["/*"] ~ ((!(["*/"]) ~ any) | block_comment)* ~ ["*/"] }
```

The only fix is to make `comment` atomic with `@`.

It seems to have something to do with defining comment as multiple rules instead of a single one.

**Comment by dragostis** [comment]
The is cause by the fact that `comment` is not forced to call `slf.set_atomic(true);`.

**Comment by sunjay** [comment]
This is pending because I believe it's already fixed in #88. If I am not mistaken about that, then this can be closed when that is merged.

@dragostis Could you confirm whether this is fixed or not?

**Comment by dragostis** [comment]
@sunjay I wouldn't close this yet since comment/whitespace logic has not been added back yet. Should leave open until I write a test that makes this case pass.

**Comment by sunjay** [comment]
Sounds good!
