### ISSUE TITLE
Matchers that do not make progress are difficult to use in error handling

### ISSUE THREAD

**Issue by sunjay** [pest-parser/pest#99]
Let's say I have a rule like this:

```rust
identifier = { !keyword ~ alpha ~ alphanumeric* }
keyword = { ["foo"] }
```

If I try to parse the word `foo`, it doesn't parse (as expected), but I don't get enough information to provide a useful error to the user.

`parser.expected()` returns `[identifier]` and all the other methods return `[]`. So the error I would report to the user is:

```
Expected an identifier
```

Notice that the rest of the rule is `alpha ~ alphanumeric*`. The word `foo` clearly matches that criteria, but the identifier rule fails to parse because of the `!keyword` part.

It would be more useful to print:
```
Expected an identifier, found a keyword instead.
```

Or something else letting them know what really happened.

This applies to all matchers that do not make progress like `!` and `&`.

**Comment by dragostis** [comment]
I'm going leave this open and hope that solving #100 will fix this as well.
